/********************* SHARE - CREACI�N DE TABLAS TEMPORALES Y STAGING **************************/

INSERT INTO TBLLOGREGIST 
VALUES (seq_TBLLOGREGIST.NEXTVAL,(SELECT ID_SCRIPT FROM TBLLOGSCRIPT WHERE DESC_SCRIPT='PROMOCIONES_SAMPLINGS_OBJETIVOS'),current_date,null,null,null,null,null,null,0);
COMMIT;

INSERT INTO TBLLOGREGEST SELECT MAX(ID_REGISTRO), 1 FROM TBLLOGREGIST WHERE ID_SCRIPT=(SELECT ID_SCRIPT FROM TBLLOGSCRIPT WHERE DESC_SCRIPT='PROMOCIONES_SAMPLINGS_OBJETIVOS'); 
COMMIT;

/****** BORRA TABLAS TEMPORALES **********/


DROP TABLE MKT_TMP_PS_OBJETIVO;

DROP SEQUENCE MKT_SEQ_PS_OBJETIVO;

/****** CREA TABLAS TEMPORALES **********/
CREATE SEQUENCE MKT_SEQ_PS_OBJETIVO;

 CREATE TABLE MKT_TMP_PS_OBJETIVO(
ID_PS_OBJETIVO NUMBER PRIMARY KEY,
CLAVE_PROMOCION NVARCHAR2(4),
NOMBRE_PROMOCION NVARCHAR2(100),
CORTE NVARCHAR2(60),
CLAVE_CORTE NVARCHAR2(10),
TM_CATEGORIA NVARCHAR2(10),
TM_RETORNABILIDAD NVARCHAR2(10),
TM_EMPAQUE NVARCHAR2(10),
TM_TAMANO NVARCHAR2(10),
TM_TPV NVARCHAR2(10),
FECHA_INICIO NVARCHAR2(20),
FECHA_FIN NVARCHAR2(20),
SKU_VENTA NVARCHAR2(20),
CANAL NVARCHAR2(30),
CF NVARCHAR2(10),
CU NVARCHAR2(10),
CFC NUMBER(10,2),
PIEZAS NUMBER(10,2),
C_ORO_TRA NUMBER(10,2),
C_PLATA_TRA NUMBER(10,2),
C_BRONCE_TRA NUMBER(10,2),
C_TRA NUMBER(10,2),
COB_ORO_TRA NUMBER(10,4),
COB_PLATA_TRA NUMBER(10,4),
COB_BRONCE_TRA NUMBER(10,4),
COB_TRA NUMBER(10,4),
C_ORO_ESP NUMBER(10,2),
C_PLATA_ESP NUMBER(10,2),
C_BRONCE_ESP NUMBER(10,2),
C_ESP NUMBER(10,2),
COB_ORO_ESP NUMBER(10,4),
COB_PLATA_ESP NUMBER(10,4),
COB_BRONCE_ESP NUMBER(10,4),
COB_ESP NUMBER(10,4),
REDENCION NUMBER(10,2),
DESCUENTOS NUMBER(10,2),
GEN_1 NUMBER(10,4),
GEN_2 NUMBER(10,4),
GEN_3 NUMBER(10,4),
GEN_4 NUMBER(10,4),
GEN_5 NUMBER(10,4),
GEN_6 NUMBER(10,4),
GEN_7 NUMBER(10,4),
GEN_8 NUMBER(10,4),
GEN_9 NUMBER(10,4),
GEN_10 NUMBER(10,4)
);