/********************* SHARE - CREACI�N DE TABLAS TEMPORALES Y STAGING **************************/

UPDATE TBLLOGREGIST SET CANTIDAD_REG=(SELECT COUNT(*) FROM MKT_ST_PS_RUTA_CANAL) WHERE ID_REGISTRO=(SELECT MAX(ID_REGISTRO) FROM TBLLOGREGIST WHERE ID_SCRIPT=(SELECT ID_SCRIPT FROM TBLLOGSCRIPT WHERE DESC_SCRIPT='PROMOCIONES_SAMPLINGS_RUTA_CANAL'));
COMMIT;

UPDATE TBLLOGREGIST SET AVANCE=100 WHERE ID_REGISTRO=(SELECT MAX(ID_REGISTRO) FROM TBLLOGREGIST WHERE ID_SCRIPT=(SELECT ID_SCRIPT FROM TBLLOGSCRIPT WHERE DESC_SCRIPT='PROMOCIONES_SAMPLINGS_RUTA_CANAL'));
COMMIT;



/****** CARGA DE TABLAS STAGIN ******/
TRUNCATE TABLE MKT_ST_PS_RUTA_CANAL;
COMMIT;
INSERT INTO MKT_ST_PS_RUTA_CANAL
SELECT RUTA_REPARTO, 
CANAL_MKT, 
SYSDATE
FROM MKT_TMP_PS_RUTA_CANAL
COMMIT;









/****** REGISTRO DE CONTROL ******/
UPDATE  TBLLOGREGEST SET ID_ESTATUS=2 WHERE ID_REGISTRO=(SELECT MAX(ID_REGISTRO) FROM TBLLOGREGIST WHERE ID_SCRIPT=(SELECT ID_SCRIPT FROM TBLLOGSCRIPT WHERE DESC_SCRIPT='PROMOCIONES_SAMPLINGS_RUTA_CANAL'));
COMMIT;

UPDATE TBLLOGREGIST SET FEC_FIN=current_date WHERE ID_REGISTRO=(SELECT MAX(ID_REGISTRO) FROM TBLLOGREGIST WHERE ID_SCRIPT=(SELECT ID_SCRIPT FROM TBLLOGSCRIPT WHERE DESC_SCRIPT='PROMOCIONES_SAMPLINGS_RUTA_CANAL'));
COMMIT;

UPDATE  TBLLOGREGEST SET ID_ESTATUS=2;
COMMIT;
