/********************* SHARE - CREACI�N DE TABLAS TEMPORALES Y STAGING **************************/

UPDATE TBLLOGREGIST SET CANTIDAD_REG=(SELECT COUNT(*) FROM MKT_TMP_LZ_FILTRO_ID_CLIENTE) WHERE ID_REGISTRO=(SELECT MAX(ID_REGISTRO) FROM TBLLOGREGIST WHERE ID_SCRIPT=(SELECT ID_SCRIPT FROM TBLLOGSCRIPT WHERE DESC_SCRIPT='LANZAMIENTOS_FILTRO_ID'));
COMMIT;

UPDATE TBLLOGREGIST SET AVANCE=100 WHERE ID_REGISTRO=(SELECT MAX(ID_REGISTRO) FROM TBLLOGREGIST WHERE ID_SCRIPT=(SELECT ID_SCRIPT FROM TBLLOGSCRIPT WHERE DESC_SCRIPT='LANZAMIENTOS_FILTRO_ID'));
COMMIT;




/****** CARGA DE TABLAS STAGIN ******/
TRUNCATE TABLE MKT_ST_LZ_FILTRO_ID_CLIENTE;
COMMIT;
INSERT INTO MKT_ST_LZ_FILTRO_ID_CLIENTE
SELECT CONSECUTIVO,
  CLAVE_LANZAMIENTO,
  NOMBRE_LANZAMIENTO,
  TO_DATE(FECHA_INICIO,'DD/MM/YYYY'),
  TO_DATE(FECHA_FIN,'DD/MM/YYYY'),
  TIPO_ENTRADA,
  ID_ENTRADA,
  CLIENTES,
  GRUPO_CANAL,
  TIPO_PREVENTA,
  TIPO_CANAL,
  DESCRIPCION_COMBO,
  OBJETIVO,
  SYSDATE
FROM MKT_TMP_LZ_FILTRO_ID_CLIENTE ;
COMMIT;

/****** REGISTRO DE CONTROL ******/
UPDATE  TBLLOGREGEST SET ID_ESTATUS=2 WHERE ID_REGISTRO=(SELECT MAX(ID_REGISTRO) FROM TBLLOGREGIST WHERE ID_SCRIPT=(SELECT ID_SCRIPT FROM TBLLOGSCRIPT WHERE DESC_SCRIPT='LANZAMIENTOS_FILTRO_ID'));
COMMIT;

UPDATE TBLLOGREGIST SET FEC_FIN=current_date WHERE ID_REGISTRO=(SELECT MAX(ID_REGISTRO) FROM TBLLOGREGIST WHERE ID_SCRIPT=(SELECT ID_SCRIPT FROM TBLLOGSCRIPT WHERE DESC_SCRIPT='LANZAMIENTOS_FILTRO_ID'));
COMMIT;

UPDATE  TBLLOGREGEST SET ID_ESTATUS=2;
COMMIT;

 