/********************* SHARE - CREACI�N DE TABLAS TEMPORALES Y STAGING **************************/

INSERT INTO TBLLOGREGIST 
VALUES (seq_TBLLOGREGIST.NEXTVAL,(SELECT ID_SCRIPT FROM TBLLOGSCRIPT WHERE DESC_SCRIPT='LANZAMIENTOS_OBJETIVOS'),current_date,null,null,null,null,null,null,0);
COMMIT;

INSERT INTO TBLLOGREGEST SELECT MAX(ID_REGISTRO), 1 FROM TBLLOGREGIST WHERE ID_SCRIPT=(SELECT ID_SCRIPT FROM TBLLOGSCRIPT WHERE DESC_SCRIPT='LANZAMIENTOS_OBJETIVOS'); 
COMMIT;


/****** BORRA TABLAS TEMPORALES **********/


DROP TABLE MKT_TMP_LZ_OBJETIVO;

DROP SEQUENCE MKT_SEQ_LZ_OBJETIVO;

/****** CREA TABLAS TEMPORALES **********/

CREATE SEQUENCE MKT_SEQ_LZ_OBJETIVO;

CREATE TABLE MKT_TMP_LZ_OBJETIVO(
ID_LZ_OBJETIVO INTEGER PRIMARY KEY,
CONSECUTIVO NVARCHAR2(10), 
CLAVE_LANZAMIENTO NVARCHAR2(10), 
NOMBRE_LANZAMIENTO NVARCHAR2(60), 
CORTE NVARCHAR2(60), 
CLAVE_CORTE NVARCHAR2(10), 
FECHA_INI_TOTAL NVARCHAR2(20), 
FECHA_FIN_TOTAL NVARCHAR2(20), 
FEHCA_INI_REAL NVARCHAR2(20), 
FECHA_FIN_REAL NVARCHAR2(20), 
TIPO_ENTRADA NVARCHAR2(3), 
ID_ENTRADA NVARCHAR2(24), 
MES NVARCHAR2(5), 
CANAL NVARCHAR2(40), 
CF NUMBER(10,2), 
CU NUMBER(10,2), 
CFC NUMBER(10,2), 
PIEZAS NUMBER(10,2), 
CLIENTES NUMBER(10,2), 
COBERUTRA_TRADICIONAL NUMBER(10,2), 
COBERTURA_ESPECIALIZADA NUMBER(10,2), 
COBERTURA_ORO_TRA NUMBER(10,2), 
COBERTURA_PLATA_TRA NUMBER(10,2), 
COBERTURA_BRONCE_TRA NUMBER(10,2), 
COBERTURA_ORO_ESP NUMBER(10,2), 
COBERTURA_PLATA_ESP NUMBER(10,2), 
COBERTURA_BRONCE_ESP NUMBER(10,2), 
RECOMPRA_TRA NUMBER(10,2), 
RECOMPRA_ESP NUMBER(10,2), 
GENERICO_1 NUMBER(10,2), 
GENERICO_2 NUMBER(10,2), 
GENERICO_3 NUMBER(10,2)
);

 