/********************* SHARE - CREACI�N DE TABLAS TEMPORALES Y STAGING **************************/

INSERT INTO TBLLOGREGIST 
VALUES (seq_TBLLOGREGIST.NEXTVAL,(SELECT ID_SCRIPT FROM TBLLOGSCRIPT WHERE DESC_SCRIPT='LANZAMIENTOS_FILTRO_ID'),current_date,null,null,null,null,null,null,0);
COMMIT;

INSERT INTO TBLLOGREGEST SELECT MAX(ID_REGISTRO), 1 FROM TBLLOGREGIST WHERE ID_SCRIPT=(SELECT ID_SCRIPT FROM TBLLOGSCRIPT WHERE DESC_SCRIPT='LANZAMIENTOS_FILTRO_ID'); 
COMMIT;

/****** BORRA TABLAS TEMPORALES **********/


DROP TABLE MKT_TMP_LZ_FILTRO_ID_CLIENTE;

DROP SEQUENCE MKT_SEQ_LZ_FILTRO_ID_CLIENTE;

/****** CREA TABLAS TEMPORALES **********/

CREATE SEQUENCE MKT_SEQ_LZ_FILTRO_ID_CLIENTE;

CREATE TABLE MKT_TMP_LZ_FILTRO_ID_CLIENTE
(ID_LZ_FILTRO_ID_CLIENTE INTEGER PRIMARY KEY,
CONSECUTIVO NVARCHAR2(10), 
CLAVE_LANZAMIENTO NVARCHAR2(10), 
NOMBRE_LANZAMIENTO NVARCHAR2(60), 
FECHA_INICIO NVARCHAR2(20), 
FECHA_FIN NVARCHAR2(20), 
TIPO_ENTRADA NVARCHAR2(3), 
ID_ENTRADA NVARCHAR2(24), 
CLIENTES NVARCHAR2(20), 
GRUPO_CANAL NVARCHAR2(60), 
TIPO_PREVENTA NVARCHAR2(40), 
TIPO_CANAL NVARCHAR2(40), 
DESCRIPCION_COMBO NVARCHAR2(200), 
OBJETIVO NUMBER(10,0)
);

 