--- DLL Marketing Lanzamientos, tablas de hechos coberturas modulo coberturas 
--TABLAS DE VENTAS
DROP TABLE MKT_LZ_FACT_OBJ_SKU_VT;
DROP TABLE MKT_LZ_FACT_OBJ_PEP_VT;
DROP TABLE MKT_LZ_AGG_OBJ_SKU_VT_REG;
DROP TABLE MKT_LZ_AGG_OBJ_PEP_VT_REG;
DROP TABLE MKT_LZ_AGG_OBJ_SKU_VT_EDO;
DROP TABLE MKT_LZ_AGG_OBJ_PEP_VT_EDO;
DROP TABLE MKT_LZ_FLITRO_PEP_VT;

-- Elminacion de Tablas
DROP TABLE MKT_LZ_FACT_OBJ_SKU_COB;
DROP TABLE MKT_LZ_FACT_OBJ_SKU_PVTA_COB;
DROP TABLE MKT_LZ_FACT_OBJ_SKU_VPT_GEC_CB;


DROP TABLE MKT_LZ_AGG_OBJ_SKU_COB_REG;
DROP TABLE MKT_LZ_AGG_SKU_PVTA_COB_REG;
DROP TABLE MKT_LZ_AGG_SKU_VPT_GEC_COB_REG;



DROP TABLE MKT_LZ_AGG_OBJ_SKU_COB_EDO;
DROP TABLE MKT_LZ_AGG_SKU_PVTA_COB_EDO;
DROP TABLE MKT_LZ_AGG_SKU_VPT_GEC_COB_EDO;




--DROP TABLE MKT_AGG_SKU_VPT_GEC_COB_EDO;
--DROP TABLE MKT_LZ_DIM_TIPO_PREVENTA;
DROP TABLE MKT_LZ_DIM_LANZAMIENTO;

-- DIMENSION LANZAMIENTO 

CREATE TABLE MKT_LZ_DIM_LANZAMIENTO(	
PK_LANZAMIENTO NUMBER (10,0) PRIMARY KEY NOT NULL,
GV_CONSECUTIVO	NVARCHAR2(10),
GV_CLAVE_LANZAMIENTO NVARCHAR2(10),	
GV_NOMBRE_LANZAMIENTO	NVARCHAR2(60)
);



-- DIMENSION TIPO PREVENTA

-- CREATE TABLE MKT_LZ_DIM_TIPO_PREVENTA(	
--PK_PREVENTA	NUMBER(10,0) PRIMARY KEY NOT NULL,
--GV_PREVENTA	VARCHAR2(30),
--GV_C_PLAN_VISITA	NVARCHAR2(10)
--);

--- Tablas de Hechos correspondientes a lanzamientos coberturas

-- TABLA DE HECHOS A NIVEL CENTRO SKU COBERTURA

CREATE TABLE MKT_LZ_FACT_OBJ_SKU_COB(	
FK_PERIODO_INICIO NUMBER(6,0),
FK_PERIODO_FIN NUMBER(6,0),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CENTRO NVARCHAR2(6),
FK_CANAL_RM1 NVARCHAR2(30),
FK_LANZAMIENTO NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MV_PERIODO_INICIO_R NUMBER(6,0),
MV_PERIODO_FIN_R NUMBER(6,0),
MV_MES NVARCHAR2(10),
MD_CLIENTES NUMBER(10,2),
MD_GEN1 NUMBER(10,2),
MD_GEN2 NUMBER(10,2),
MD_GEN3 NUMBER(10,2)
);


ALTER TABLE MKT_LZ_FACT_OBJ_SKU_COB
ADD CONSTRAINT LZ_MKT_LZ_FACT_OBJ_SKU_COB
FOREIGN KEY(FK_LANZAMIENTO)
REFERENCES MKT_LZ_DIM_LANZAMIENTO(PK_LANZAMIENTO);

ALTER TABLE MKT_LZ_FACT_OBJ_SKU_COB
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CENTRO,
FK_CANAL_RM1,
FK_LANZAMIENTO,
FK_SKU,
MV_MES
);






-- TABLA DE HECHOS A NIVEL CENTRO SKU PREVENTA COBERTURA

CREATE TABLE MKT_LZ_FACT_OBJ_SKU_PVTA_COB(	
FK_PERIODO_INICIO NUMBER(6,0),
FK_PERIODO_FIN NUMBER(6,0),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CENTRO NVARCHAR2(6),
FK_CANAL_RM1 NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_LANZAMIENTO NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MV_PERIODO_INICIO_R NUMBER(6,0),
MV_PERIODO_FIN_R NUMBER(6,0),
MV_MES NVARCHAR2(10),
MD_COBERTURA NUMBER(10,2),
MD_RECOMPRA NUMBER(10,2)
);



ALTER TABLE MKT_LZ_FACT_OBJ_SKU_PVTA_COB	
ADD CONSTRAINT PVTA_MKTLZFACTOBJSKUPVTACOB
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_LZ_FACT_OBJ_SKU_PVTA_COB
ADD CONSTRAINT LZMKTLZFACTOBJSKUPVTACOB
FOREIGN KEY(FK_LANZAMIENTO)
REFERENCES MKT_LZ_DIM_LANZAMIENTO(PK_LANZAMIENTO);

ALTER TABLE MKT_LZ_FACT_OBJ_SKU_PVTA_COB
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CENTRO,
FK_CANAL_RM1,
FK_PREVENTA,
FK_LANZAMIENTO,
FK_SKU,
MV_MES
);




-- TABLA DE HECHOS A NIVEL CENTRO SKU PREVENTA GEC COBERTURA

CREATE TABLE MKT_LZ_FACT_OBJ_SKU_VPT_GEC_CB(	
FK_PERIODO_INICIO NUMBER(6,0),
FK_PERIODO_FIN NUMBER(6,0),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CENTRO NVARCHAR2(6),
FK_CANAL_RM1 NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_GEC NVARCHAR2(4),
FK_LANZAMIENTO NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MV_PERIODO_INICIO_R NUMBER(6,0),
MV_PERIODO_FIN_R NUMBER(6,0),
MV_MES NVARCHAR2(10),
MD_COBERTURA NUMBER(10,2)
);


ALTER TABLE MKT_LZ_FACT_OBJ_SKU_VPT_GEC_CB	
ADD CONSTRAINT PVTAMKTLZFACTOBJSKUVPTGECCB
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_LZ_FACT_OBJ_SKU_VPT_GEC_CB
ADD CONSTRAINT LZMKTLZFACTOBJSKUVPTGECCOB
FOREIGN KEY(FK_LANZAMIENTO)
REFERENCES MKT_LZ_DIM_LANZAMIENTO(PK_LANZAMIENTO);

ALTER TABLE MKT_LZ_FACT_OBJ_SKU_VPT_GEC_CB
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CENTRO,
FK_CANAL_RM1,
FK_PREVENTA,
FK_GEC,
FK_LANZAMIENTO,
FK_SKU,
MV_MES
);


-----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------
--------------------------------------TABLAS AGREGADAS REGION ---------------------------------------
-----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------
--MKT_LZ_AGG_OBJ_SKU_COB_REG
--MKT_LZ_AGG_OBJ_SKU_PVTA_COB_REG	
--MKT_AGG_OBJ_SKU_VPT_GEC_COB_REG

-- TABLA DE HECHOS A NIVEL REGION SKU COBERTURA

CREATE TABLE MKT_LZ_AGG_OBJ_SKU_COB_REG(	
FK_PERIODO_INICIO NUMBER(6,0),
FK_PERIODO_FIN NUMBER(6,0),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CANAL_RM1 NVARCHAR2(30),
FK_LANZAMIENTO NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MV_PERIODO_INICIO_R NUMBER(6,0),
MV_PERIODO_FIN_R NUMBER(6,0),
MV_MES NVARCHAR2(10),
MD_CLIENTES NUMBER(10,2),
MD_GEN1 NUMBER(10,2),
MD_GEN2 NUMBER(10,2),
MD_GEN3 NUMBER(10,2)
);


ALTER TABLE MKT_LZ_AGG_OBJ_SKU_COB_REG
ADD CONSTRAINT LZ_MKT_LZ_AGG_OBJ_SKU_COB
FOREIGN KEY(FK_LANZAMIENTO)
REFERENCES MKT_LZ_DIM_LANZAMIENTO(PK_LANZAMIENTO);

ALTER TABLE MKT_LZ_AGG_OBJ_SKU_COB_REG
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CANAL_RM1,
FK_LANZAMIENTO,
FK_SKU,
MV_MES
);






-- TABLA DE HECHOS A NIVEL REGION SKU PREVENTA COBERTURA


CREATE TABLE MKT_LZ_AGG_SKU_PVTA_COB_REG(	
FK_PERIODO_INICIO NUMBER(6,0),
FK_PERIODO_FIN NUMBER(6,0),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CANAL_RM1 NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_LANZAMIENTO NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MV_PERIODO_INICIO_R NUMBER(6,0),
MV_PERIODO_FIN_R NUMBER(6,0),
MV_MES NVARCHAR2(10),
MD_COBERTURA NUMBER(10,2),
MD_RECOMPRA NUMBER(10,2)
);



ALTER TABLE MKT_LZ_AGG_SKU_PVTA_COB_REG	
ADD CONSTRAINT PVTA_MKT_LZ_AGG_SKU_PVTA_COB
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_LZ_AGG_SKU_PVTA_COB_REG
ADD CONSTRAINT LZ_MKT_LZ_AGG_SKU_PVTA_COB
FOREIGN KEY(FK_LANZAMIENTO)
REFERENCES MKT_LZ_DIM_LANZAMIENTO(PK_LANZAMIENTO);

ALTER TABLE MKT_LZ_AGG_SKU_PVTA_COB_REG
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CANAL_RM1,
FK_PREVENTA,
FK_LANZAMIENTO,
FK_SKU,
MV_MES
);




-- TABLA DE HECHOS A NIVEL REGION SKU PREVENTA GEC COBERTURA
	

CREATE TABLE MKT_LZ_AGG_SKU_VPT_GEC_COB_REG(	
FK_PERIODO_INICIO NUMBER(6,0),
FK_PERIODO_FIN NUMBER(6,0),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CANAL_RM1 NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_GEC NVARCHAR2(4),
FK_LANZAMIENTO NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MV_PERIODO_INICIO_R NUMBER(6,0),
MV_PERIODO_FIN_R NUMBER(6,0),
MV_MES NVARCHAR2(10),
MD_COBERTURA NUMBER(10,2)
);


ALTER TABLE MKT_LZ_AGG_SKU_VPT_GEC_COB_REG	
ADD CONSTRAINT PVTA_MKT_LZ_SKU_VPT_GEC_COB
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_LZ_AGG_SKU_VPT_GEC_COB_REG
ADD CONSTRAINT LZ_MKT_LZ_OBJ_SKU_VPT_GEC_COB
FOREIGN KEY(FK_LANZAMIENTO)
REFERENCES MKT_LZ_DIM_LANZAMIENTO(PK_LANZAMIENTO);

ALTER TABLE MKT_LZ_AGG_SKU_VPT_GEC_COB_REG
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CANAL_RM1,
FK_PREVENTA,
FK_GEC,
FK_LANZAMIENTO,
FK_SKU,
MV_MES
);


-----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------
--------------------------------------TABLAS AGREGADAS ESTADO ---------------------------------------
-----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------
--MKT_LZ_AGG_OBJ_SKU_COB_EDO
--MKT_LZ_AGG_OBJ_SKU_PVTA_COB_EDO
--MKT_AGG_OBJ_SKU_VPT_GEC_COB_EDO

-- TABLA DE HECHOS A NIVEL REGION SKU COBERTURA

CREATE TABLE MKT_LZ_AGG_OBJ_SKU_COB_EDO(	
FK_PERIODO_INICIO NUMBER(6,0),
FK_PERIODO_FIN NUMBER(6,0),
FK_ESTADO NVARCHAR2(3),
FK_CANAL_RM1 NVARCHAR2(30),
FK_LANZAMIENTO NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MV_PERIODO_INICIO_R NUMBER(6,0),
MV_PERIODO_FIN_R NUMBER(6,0),
MV_MES NVARCHAR2(10),
MD_CLIENTES NUMBER(10,2),
MD_GEN1 NUMBER(10,2),
MD_GEN2 NUMBER(10,2),
MD_GEN3 NUMBER(10,2)
);


ALTER TABLE MKT_LZ_AGG_OBJ_SKU_COB_EDO
ADD CONSTRAINT LZ_MKT_LZ_AGG2_OBJ_SKU_COB
FOREIGN KEY(FK_LANZAMIENTO)
REFERENCES MKT_LZ_DIM_LANZAMIENTO(PK_LANZAMIENTO);

ALTER TABLE MKT_LZ_AGG_OBJ_SKU_COB_EDO
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_CANAL_RM1,
FK_LANZAMIENTO,
FK_SKU,
MV_MES
);






-- TABLA DE HECHOS A NIVEL REGION SKU PREVENTA COBERTURA


CREATE TABLE MKT_LZ_AGG_SKU_PVTA_COB_EDO(	
FK_PERIODO_INICIO NUMBER(6,0),
FK_PERIODO_FIN NUMBER(6,0),
FK_ESTADO NVARCHAR2(3),
FK_CANAL_RM1 NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_LANZAMIENTO NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MV_PERIODO_INICIO_R NUMBER(6,0),
MV_PERIODO_FIN_R NUMBER(6,0),
MV_MES NVARCHAR2(10),
MD_COBERTURA NUMBER(10,2),
MD_RECOMPRA NUMBER(10,2)
);



ALTER TABLE MKT_LZ_AGG_SKU_PVTA_COB_EDO	
ADD CONSTRAINT PVTA_MKT_LZ_AGG2_SKU_PVTA_COB
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_LZ_AGG_SKU_PVTA_COB_EDO
ADD CONSTRAINT LZ_MKT_LZ_AGG2_SKU_PVTA_COB
FOREIGN KEY(FK_LANZAMIENTO)
REFERENCES MKT_LZ_DIM_LANZAMIENTO(PK_LANZAMIENTO);

ALTER TABLE MKT_LZ_AGG_SKU_PVTA_COB_EDO
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_CANAL_RM1,
FK_PREVENTA,
FK_LANZAMIENTO,
FK_SKU,
MV_MES
);




-- TABLA DE HECHOS A NIVEL REGION SKU PREVENTA GEC COBERTURA
	

CREATE TABLE MKT_LZ_AGG_SKU_VPT_GEC_COB_EDO(	
FK_PERIODO_INICIO NUMBER(6,0),
FK_PERIODO_FIN NUMBER(6,0),
FK_ESTADO NVARCHAR2(3),
FK_CANAL_RM1 NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_GEC NVARCHAR2(4),
FK_LANZAMIENTO NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MV_PERIODO_INICIO_R NUMBER(6,0),
MV_PERIODO_FIN_R NUMBER(6,0),
MV_MES NVARCHAR2(10),
MD_COBERTURA NUMBER(10,2)
);


ALTER TABLE MKT_LZ_AGG_SKU_VPT_GEC_COB_EDO
ADD CONSTRAINT PVTA_LZ_AGG2_SKU_VPT_GEC_COB
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_LZ_AGG_SKU_VPT_GEC_COB_EDO
ADD CONSTRAINT LZ_LZ_AGG2_SKU_VPT_GEC_COB
FOREIGN KEY(FK_LANZAMIENTO)
REFERENCES MKT_LZ_DIM_LANZAMIENTO(PK_LANZAMIENTO);

ALTER TABLE MKT_LZ_AGG_SKU_VPT_GEC_COB_EDO
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_CANAL_RM1,
FK_PREVENTA,
FK_GEC,
FK_LANZAMIENTO,
FK_SKU,
MV_MES
);

COMMIT;