-- DLL TABLAS DE HECHOS PARA TABLAS DE HECHOS LANZAMIENTOS VENTAS 

-- DROP TABLE MKT_LZ_FACT_OBJ_SKU_VT;
-- DROP TABLE MKT_LZ_FACT_OBJ_PEP_VT;
-- DROP TABLE MKT_LZ_AGG_OBJ_SKU_VT_REG;
-- DROP TABLE MKT_LZ_AGG_OBJ_PEP_VT_REG;
-- DROP TABLE MKT_LZ_AGG_OBJ_SKU_VT_EDO;
-- DROP TABLE MKT_LZ_AGG_OBJ_PEP_VT_EDO;
-- DROP TABLE MKT_LZ_FLITRO_PEP_VT;



-- TABLA DE HECHOS A NIVEL CENTRO SKU

CREATE TABLE MKT_LZ_FACT_OBJ_SKU_VT(	
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CENTRO NVARCHAR2(6),
FK_CANAL_RM1 NVARCHAR2(30),
FK_LANZAMIENTO NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MV_PERIODO_INICIO_R NVARCHAR2(10),
MV_PERIODO_FIN_R NVARCHAR2(10),
MV_MES NVARCHAR2(10),
MD_CF NUMBER(10,2),
MD_CFC NUMBER(10,2),
MD_CU NUMBER(10,2),
MD_PIEZAS NUMBER(10,2),
MD_GEN1 NUMBER(10,2),
MD_GEN2 NUMBER(10,2),
MD_GEN3 NUMBER(10,2)
);



ALTER TABLE MKT_LZ_FACT_OBJ_SKU_VT
ADD CONSTRAINT MKT_LZ_FACT_OBJ_SKU_VT
FOREIGN KEY(FK_LANZAMIENTO)
REFERENCES MKT_LZ_DIM_LANZAMIENTO(PK_LANZAMIENTO);

ALTER TABLE MKT_LZ_FACT_OBJ_SKU_VT
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CENTRO,
FK_CANAL_RM1,
FK_LANZAMIENTO,
FK_SKU,
MV_MES
);




-- TABLA DE HECHOS A NIVEL CENTRO PEP
CREATE TABLE MKT_LZ_FACT_OBJ_PEP_VT(	
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CENTRO NVARCHAR2(6),
FK_CANAL_RM1 NVARCHAR2(30),
FK_LANZAMIENTO NUMBER(10,0),
FK_PEP NVARCHAR2(24),
MV_PERIODO_INICIO_R NVARCHAR2(10),
MV_PERIODO_FIN_R NVARCHAR2(10),
MV_MES NVARCHAR2(10),
MD_CF NUMBER(10,2),
MD_CFC NUMBER(10,2),
MD_CU NUMBER(10,2),
MD_PIEZAS NUMBER(10,2),
MD_GEN1 NUMBER(10,2),
MD_GEN2 NUMBER(10,2),
MD_GEN3 NUMBER(10,2)
);


ALTER TABLE MKT_LZ_FACT_OBJ_PEP_VT
ADD CONSTRAINT MKT_LZ_FACT_OBJ_PEP_VT
FOREIGN KEY(FK_LANZAMIENTO)
REFERENCES MKT_LZ_DIM_LANZAMIENTO(PK_LANZAMIENTO);

ALTER TABLE MKT_LZ_FACT_OBJ_PEP_VT
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CENTRO,
FK_CANAL_RM1,
FK_LANZAMIENTO,
FK_PEP,
MV_MES
);





-----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------
--------------------------------------TABLAS AGREGADAS REGI�N ---------------------------------------
-----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------


-- TABLA DE HECHOS A NIVEL REGI�N SKU

CREATE TABLE MKT_LZ_AGG_OBJ_SKU_VT_REG(	
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CANAL_RM1 NVARCHAR2(30),
FK_LANZAMIENTO NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MV_PERIODO_INICIO_R NVARCHAR2(10),
MV_PERIODO_FIN_R NVARCHAR2(10),
MV_MES NVARCHAR2(10),
MD_CF NUMBER(10,2),
MD_CFC NUMBER(10,2),
MD_CU NUMBER(10,2),
MD_PIEZAS NUMBER(10,2),
MD_GEN1 NUMBER(10,2),
MD_GEN2 NUMBER(10,2),
MD_GEN3 NUMBER(10,2)
);


ALTER TABLE MKT_LZ_AGG_OBJ_SKU_VT_REG
ADD CONSTRAINT MKT_LZ_AGG_OBJ_SKU_VT_REG
FOREIGN KEY(FK_LANZAMIENTO)
REFERENCES MKT_LZ_DIM_LANZAMIENTO(PK_LANZAMIENTO);

ALTER TABLE MKT_LZ_AGG_OBJ_SKU_VT_REG
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CANAL_RM1,
FK_LANZAMIENTO,
FK_SKU,
MV_MES
);




-- TABLA DE HECHOS A NIVEL CENTRO PEP
CREATE TABLE MKT_LZ_AGG_OBJ_PEP_VT_REG(	
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CANAL_RM1 NVARCHAR2(30),
FK_LANZAMIENTO NUMBER(10,0),
FK_PEP NVARCHAR2(24),
MV_PERIODO_INICIO_R NVARCHAR2(10),
MV_PERIODO_FIN_R NVARCHAR2(10),
MV_MES NVARCHAR2(10),
MD_CF NUMBER(10,2),
MD_CFC NUMBER(10,2),
MD_CU NUMBER(10,2),
MD_PIEZAS NUMBER(10,2),
MD_GEN1 NUMBER(10,2),
MD_GEN2 NUMBER(10,2),
MD_GEN3 NUMBER(10,2)
);


ALTER TABLE MKT_LZ_AGG_OBJ_PEP_VT_REG
ADD CONSTRAINT MKT_LZ_AGG_OBJ_PEP_VT_REG
FOREIGN KEY(FK_LANZAMIENTO)
REFERENCES MKT_LZ_DIM_LANZAMIENTO(PK_LANZAMIENTO);

ALTER TABLE MKT_LZ_AGG_OBJ_PEP_VT_REG
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CANAL_RM1,
FK_LANZAMIENTO,
FK_PEP,
MV_MES
);

-----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------
--------------------------------------TABLAS AGREGADAS ESTADO ---------------------------------------
-----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------


-- TABLA DE HECHOS A NIVEL REGI�N SKU

CREATE TABLE MKT_LZ_AGG_OBJ_SKU_VT_EDO(	
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_CANAL_RM1 NVARCHAR2(30),
FK_LANZAMIENTO NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MV_PERIODO_INICIO_R NVARCHAR2(10),
MV_PERIODO_FIN_R NVARCHAR2(10),
MV_MES NVARCHAR2(10),
MD_CF NUMBER(10,2),
MD_CFC NUMBER(10,2),
MD_CU NUMBER(10,2),
MD_PIEZAS NUMBER(10,2),
MD_GEN1 NUMBER(10,2),
MD_GEN2 NUMBER(10,2),
MD_GEN3 NUMBER(10,2)
);


ALTER TABLE MKT_LZ_AGG_OBJ_SKU_VT_EDO
ADD CONSTRAINT MKT_LZ_AGG_OBJ_SKU_VT_EDO
FOREIGN KEY(FK_LANZAMIENTO)
REFERENCES MKT_LZ_DIM_LANZAMIENTO(PK_LANZAMIENTO);

ALTER TABLE MKT_LZ_AGG_OBJ_SKU_VT_EDO
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_CANAL_RM1,
FK_LANZAMIENTO,
FK_SKU,
MV_MES
);




-- TABLA DE HECHOS A NIVEL CENTRO PEP
CREATE TABLE MKT_LZ_AGG_OBJ_PEP_VT_EDO(	
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_CANAL_RM1 NVARCHAR2(30),
FK_LANZAMIENTO NUMBER(10,0),
FK_PEP NVARCHAR2(24),
MV_PERIODO_INICIO_R NVARCHAR2(10),
MV_PERIODO_FIN_R NVARCHAR2(10),
MV_MES NVARCHAR2(10),
MD_CF NUMBER(10,2),
MD_CFC NUMBER(10,2),
MD_CU NUMBER(10,2),
MD_PIEZAS NUMBER(10,2),
MD_GEN1 NUMBER(10,2),
MD_GEN2 NUMBER(10,2),
MD_GEN3 NUMBER(10,2)
);




ALTER TABLE MKT_LZ_AGG_OBJ_PEP_VT_EDO
ADD CONSTRAINT MKT_LZ_AGG_OBJ_PEP_VT_EDO
FOREIGN KEY(FK_LANZAMIENTO)
REFERENCES MKT_LZ_DIM_LANZAMIENTO(PK_LANZAMIENTO);

ALTER TABLE MKT_LZ_AGG_OBJ_PEP_VT_EDO
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_CANAL_RM1,
FK_LANZAMIENTO,
FK_PEP,
MV_MES
);




-----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------
--------------------------------------TABLA DE HECHOS FLITRO CLIENTE ---------------------------------------
-----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------

-- TABLA DE HECHOS A NIVEL CENTRO PEP
CREATE TABLE MKT_LZ_FLITRO_PEP_VT(	
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CANAL NVARCHAR2(30),
FK_LANZAMIENTO NUMBER(10,0),
FK_PREVENTA NUMBER(10,0),
FK_PEP NVARCHAR2(24),
FK_CLIENTE NVARCHAR2(18),
MD_OBJETIVO NUMBER(10,2)
);


ALTER TABLE MKT_LZ_FLITRO_PEP_VT
ADD CONSTRAINT MKT_LZ_FLITRO_PEP_VT_LZ
FOREIGN KEY(FK_LANZAMIENTO)
REFERENCES MKT_LZ_DIM_LANZAMIENTO(PK_LANZAMIENTO);


ALTER TABLE MKT_LZ_FLITRO_PEP_VT
ADD CONSTRAINT MKT_LZ_FLITRO_PEP_VT_PVT
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);


ALTER TABLE MKT_LZ_FLITRO_PEP_VT
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_CANAL_RM1,
FK_CANAL,
FK_LANZAMIENTO,
FK_PREVENTA,
FK_PEP,
FK_CLIENTE
);


COMMIT;