INSERT INTO TBLLOGREGIST 
VALUES (seq_TBLLOGREGIST.NEXTVAL,(SELECT ID_SCRIPT FROM TBLLOGSCRIPT WHERE DESC_SCRIPT='LANZAMIENTOS_PROCESO'),current_date,null,null,null,0);
COMMIT;

INSERT INTO TBLLOGREGEST SELECT MAX(ID_REGISTRO), 1 FROM TBLLOGREGIST WHERE ID_SCRIPT=(SELECT ID_SCRIPT FROM TBLLOGSCRIPT WHERE DESC_SCRIPT='LANZAMIENTOS_PROCESO'); 
COMMIT;




-- CREATE TABLE MKT_ST_GEC(
-- CLAVE_GEC NVARCHAR2(4),
-- GEC NVARCHAR2(20)
-- );
-- 
-- CREATE TABLE MKT_GEOGRAFIA(
-- ESTADO NVARCHAR2(3),
-- REGION_ZONA NVARCHAR2(3),
-- CENTRO NVARCHAR2(6),
-- UNIDAD_OPERATIVA NVARCHAR2(5)
-- );
-- 
-- 
-- CREATE TABLE MKT_GEC(
-- CLAVE_GEC NVARCHAR2(5),
-- GEC NVARCHAR2(15));
-- 
-- 
-- INSERT INTO MKT_GEOGRAFIA VALUES('9','ZPL','MR0080','MJMG');
-- 
-- SELECT * FROM MKT_PS_FACT_VTA_SKU;
-- 
-- INSERT INTO MKT_LZ_DIM_TIPO_PREVENTA(
-- SELECT * FROM MKT_LZ_DIM_TIPO_PREVENTA@DSE
-- );
-- 
-- 
-- 
-- INSERT INTO MKT_ST_LZ_FILTRO_ID_CLIENTE
-- SELECT * FROM  MKT_ST_LZ_FILTRO_ID_CLIENTE@DSE;
-- 
-- INSERT INTO MKT_ST_LZ_OBJETIVO
-- SELECT * FROM MKT_ST_LZ_OBJETIVO@DSE;
-- 
-- COMMIT;



TRUNCATE TABLE MKT_GEOGRAFIA;
INSERT INTO MKT_GEOGRAFIA
SELECT * FROM MKT_ST_GEOGRAFIA;
COMMIT;
---------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------

-- MKT_SEQ_LANZAMIENTO

--SELECT * FROM MKT_ST_LZ_OBJETIVO;

DROP SEQUENCE MKT_SEQ_LANZAMIENTO;
COMMIT;
--Dimensiones


--CARGA DE DIMENSION LANZAMIENTO

--SELECT * FROM MKT_LZ_DIM_LANZAMIENTO;

CREATE SEQUENCE MKT_SEQ_LANZAMIENTO
MINVALUE 1
START WITH 1
INCREMENT BY 1;

INSERT INTO MKT_LZ_DIM_LANZAMIENTO(
SELECT MKT_SEQ_LANZAMIENTO.NEXTVAL, CONSECUTIVO, CLAVE_LANZAMIENTO, NOMBRE_LANZAMIENTO FROM(
SELECT DISTINCT CONSECUTIVO, CLAVE_LANZAMIENTO, NOMBRE_LANZAMIENTO FROM MKT_ST_LZ_OBJETIVO
UNION
SELECT DISTINCT CONSECUTIVO, CLAVE_LANZAMIENTO, NOMBRE_LANZAMIENTO FROM MKT_ST_LZ_FILTRO_ID_CLIENTE
)
);

COMMIT;


-- UPDATE MKT_ST_LZ_OBJETIVO SET CLAVE_LANZAMIENTO='#';
-- UPDATE MKT_LZ_DIM_LANZAMIENTO SET GV_CLAVE_LANZAMIENTO='#';
-- UPDATE MKT_ST_LZ_FILTRO_ID_CLIENTE SET CLAVE_LANZAMIENTO='#';
-- 
-- COMMIT;


-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
----------------------- LLENADO DE TABLA DE HECHOS PARA OBJETIVOS DE COBERTURA SIN GEC NI PREVENTA POR SKU-------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------

--TABLA DE HECHOS A CENTRO

INSERT INTO MKT_LZ_FACT_OBJ_SKU_COB(
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
G.REGION_ZONA,
OB.CLAVE_CORTE,
OB.CANAL,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.CLIENTES,
OB.GENERICO_1,
OB.GENERICO_2,
OB.GENERICO_3
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.CENTRO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='UNIDAD OPERATIVA'
AND OB.TIPO_ENTRADA='SKU')
;




--COBERTURA DIFERENTE DE NULL??
--SELECT * FROM MKT_ST_LZ_OBJETIVO;



COMMIT;
-- -- LLENADO DE TABLA AGREGADA POR REGION PARA OBJETIVOS DE COBERTURA SIN GEC NI PREVENTA POR SKU

INSERT INTO MKT_LZ_AGG_OBJ_SKU_COB_REG(
SELECT PERIODO_INICIO,
PERIODO_FIN,
ESTADO,
REGION_ZONA,
CANAL,
PK_LANZAMIENTO,
SKU,
PIR,
PIF,
MES,
(CLIENTES),
(GENERICO_1),
(GENERICO_2),
(GENERICO_3)
FROM(
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
OB.CLAVE_CORTE AS REGION_ZONA,
OB.CANAL,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
(OB.CLIENTES),
(OB.GENERICO_1),
(OB.GENERICO_2),
(OB.GENERICO_3)
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.REGION_ZONA=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='REGION'
AND OB.TIPO_ENTRADA='SKU')); 


--WHERE ESTADO IN (SELECT ESTADO FROM MKT_GEOGRAFIA)
-- TABLA TEMPORAL DE COMBINACIONES PARA INSERTAR 
CREATE TABLE MKT_LZ_COB_ETL_AGG1 AS(
SELECT FK_PERIODO_INICIO,
  FK_PERIODO_FIN,
  FK_ESTADO,
  FK_REGION,
  FK_CANAL_RM1,
  FK_LANZAMIENTO,
  FK_SKU,
  MV_PERIODO_INICIO_R,
  MV_PERIODO_FIN_R,
  MV_MES
 FROM MKT_LZ_FACT_OBJ_SKU_COB 
  MINUS
SELECT FK_PERIODO_INICIO,
  FK_PERIODO_FIN,
  FK_ESTADO,
  FK_REGION,
  FK_CANAL_RM1,
  FK_LANZAMIENTO,
  FK_SKU,
  MV_PERIODO_INICIO_R,
  MV_PERIODO_FIN_R,
  MV_MES
 FROM MKT_LZ_AGG_OBJ_SKU_COB_REG) ;
 
-- COMPARANDO E INSERTANDO REGISTROS 
INSERT INTO MKT_LZ_AGG_OBJ_SKU_COB_REG(
 SELECT A.FK_PERIODO_INICIO,
  A.FK_PERIODO_FIN,
  A.FK_ESTADO,
  A.FK_REGION,
  A.FK_CANAL_RM1,
  A.FK_LANZAMIENTO,
  A.FK_SKU,
  A.MV_PERIODO_INICIO_R,
  A.MV_PERIODO_FIN_R,
  A.MV_MES,
  SUM(A.MD_CLIENTES),
  SUM(A.MD_GEN1),
  SUM(A.MD_GEN2),
  SUM(A.MD_GEN3)
FROM MKT_LZ_FACT_OBJ_SKU_COB A, MKT_LZ_COB_ETL_AGG1 B
WHERE
A.FK_PERIODO_FIN=B.FK_PERIODO_FIN
AND A.FK_ESTADO=B.FK_ESTADO
AND A.FK_REGION=B.FK_REGION
AND A.FK_CANAL_RM1=B.FK_CANAL_RM1
AND A.FK_LANZAMIENTO=B.FK_LANZAMIENTO
AND A.FK_SKU=B.FK_SKU
AND NVL(A.MV_PERIODO_INICIO_R,'0')=NVL(B.MV_PERIODO_INICIO_R,'0')
AND NVL(A.MV_PERIODO_FIN_R,'0')=NVL(B.MV_PERIODO_FIN_R,'0')
AND NVL(A.MV_MES,'0')=NVL(B.MV_MES,'0')
group by
A.FK_PERIODO_FIN, A.FK_ESTADO, A.FK_REGION, A.FK_CANAL_RM1, A.FK_LANZAMIENTO, 
A.FK_SKU, A.MV_PERIODO_INICIO_R, A.MV_PERIODO_FIN_R, A.MV_MES, A.FK_PERIODO_INICIO);

-- TABLA AGREGADA POR ESTADO

INSERT INTO MKT_LZ_AGG_OBJ_SKU_COB_EDO(
SELECT PERIODO_INICIO,
PERIODO_FIN,
ESTADO,
CANAL,
PK_LANZAMIENTO,
SKU,
PIR,
PIF,
MES,
(CLIENTES),
(GENERICO_1),
(GENERICO_2),
(GENERICO_3)
FROM(
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
OB.CLAVE_CORTE AS ESTADO,
OB.CANAL,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
(OB.CLIENTES),
(OB.GENERICO_1),
(OB.GENERICO_2),
(OB.GENERICO_3)
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.ESTADO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='ESTADO'
AND OB.TIPO_ENTRADA='SKU')); 


-- TABLA TEMPORAL DE COMBINACIONES PARA INSERTAR 
CREATE TABLE MKT_LZ_COB_ETL_AGG2 AS(
SELECT FK_PERIODO_INICIO,
  FK_PERIODO_FIN,
  FK_ESTADO,
  FK_CANAL_RM1,
  FK_LANZAMIENTO,
  FK_SKU,
  MV_PERIODO_INICIO_R,
  MV_PERIODO_FIN_R,
  MV_MES
 FROM MKT_LZ_AGG_OBJ_SKU_COB_REG
  MINUS
SELECT FK_PERIODO_INICIO,
  FK_PERIODO_FIN,
  FK_ESTADO,
  FK_CANAL_RM1,
  FK_LANZAMIENTO,
  FK_SKU,
  MV_PERIODO_INICIO_R,
  MV_PERIODO_FIN_R,
  MV_MES
 FROM MKT_LZ_AGG_OBJ_SKU_COB_EDO) ;
 
-- COMPARANDO E INSERTANDO REGISTROS 
INSERT INTO MKT_LZ_AGG_OBJ_SKU_COB_EDO(
 SELECT A.FK_PERIODO_INICIO,
  A.FK_PERIODO_FIN,
  A.FK_ESTADO,
  A.FK_CANAL_RM1,
  A.FK_LANZAMIENTO,
  A.FK_SKU,
  A.MV_PERIODO_INICIO_R,
  A.MV_PERIODO_FIN_R,
  A.MV_MES,
  SUM(A.MD_CLIENTES),
  SUM(A.MD_GEN1),
  SUM(A.MD_GEN2),
  SUM(A.MD_GEN3)
FROM MKT_LZ_AGG_OBJ_SKU_COB_REG A, MKT_LZ_COB_ETL_AGG2 B
WHERE
A.FK_PERIODO_FIN=B.FK_PERIODO_FIN
AND A.FK_ESTADO=B.FK_ESTADO
AND A.FK_CANAL_RM1=B.FK_CANAL_RM1
AND A.FK_LANZAMIENTO=B.FK_LANZAMIENTO
AND A.FK_SKU=B.FK_SKU
AND NVL(A.MV_PERIODO_INICIO_R,'0')=NVL(B.MV_PERIODO_INICIO_R,'0')
AND NVL(A.MV_PERIODO_FIN_R,'0')=NVL(B.MV_PERIODO_FIN_R,'0')
AND NVL(A.MV_MES,'0')=NVL(B.MV_MES,'0')
group by
A.FK_PERIODO_FIN, A.FK_ESTADO, A.FK_CANAL_RM1, A.FK_LANZAMIENTO, 
A.FK_SKU, A.MV_PERIODO_INICIO_R, A.MV_PERIODO_FIN_R, A.MV_MES, A.FK_PERIODO_INICIO);



DROP TABLE MKT_LZ_COB_ETL_AGG1;
DROP TABLE MKT_LZ_COB_ETL_AGG2;

COMMIT;

-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
----------------------- LLENADO DE TABLA DE HECHOS PARA OBJETIVOS DE COBERTURA SIN GEC POR SKU Y PREVENTA-------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------

--TABLA DE HECHOS A CENTRO
--SELECT * FROM MKT_ST_LZ_OBJETIVO;
INSERT INTO MKT_LZ_FACT_OBJ_SKU_PVTA_COB(
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
G.REGION_ZONA,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Tradicional' AND  ROWNUM =1) AS TIPO_PREVENTA,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERUTRA_TRADICIONAL,
OB.RECOMPRA_TRA
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.CENTRO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='UNIDAD OPERATIVA'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
G.REGION_ZONA,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Especializada' AND  ROWNUM =1) AS TIPO_PREVENTA,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_ESPECIALIZADA,
OB.RECOMPRA_ESP
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.CENTRO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='UNIDAD OPERATIVA'
AND OB.TIPO_ENTRADA='SKU');

COMMIT;

-- -- LLENADO DE TABLA AGREGADA POR REGION PARA OBJETIVOS DE COBERTURA SIN GEC POR SKU Y PREVENTA
INSERT INTO MKT_LZ_AGG_SKU_PVTA_COB_REG(
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Tradicional' AND  ROWNUM =1) AS TIPO_PREVENTA,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERUTRA_TRADICIONAL,
OB.RECOMPRA_TRA
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.REGION_ZONA=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='REGION'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Especializada' AND  ROWNUM =1) AS TIPO_PREVENTA,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_ESPECIALIZADA,
OB.RECOMPRA_ESP
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.REGION_ZONA=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='REGION'
AND OB.TIPO_ENTRADA='SKU');


--WHERE ESTADO IN (SELECT ESTADO FROM MKT_GEOGRAFIA)
-- TABLA TEMPORAL DE COMBINACIONES PARA INSERTAR 
CREATE TABLE MKT_LZ_COB_ETL_AGG1 AS(
SELECT FK_PERIODO_INICIO,
  FK_PERIODO_FIN,
  FK_ESTADO,
  FK_REGION,
  FK_CANAL_RM1,
  FK_PREVENTA,
  FK_LANZAMIENTO,
  FK_SKU,
  MV_PERIODO_INICIO_R,
  MV_PERIODO_FIN_R,
  MV_MES
 FROM MKT_LZ_FACT_OBJ_SKU_PVTA_COB 
  MINUS
SELECT FK_PERIODO_INICIO,
  FK_PERIODO_FIN,
  FK_ESTADO,
  FK_REGION,
  FK_CANAL_RM1,
  FK_PREVENTA,
  FK_LANZAMIENTO,
  FK_SKU,
  MV_PERIODO_INICIO_R,
  MV_PERIODO_FIN_R,
  MV_MES
 FROM MKT_LZ_AGG_SKU_PVTA_COB_REG) ;
 COMMIT;
 
-- COMPARANDO E INSERTANDO REGISTROS 
INSERT INTO MKT_LZ_AGG_SKU_PVTA_COB_REG(
 SELECT A.FK_PERIODO_INICIO,
  A.FK_PERIODO_FIN,
  A.FK_ESTADO,
  A.FK_REGION,
  A.FK_CANAL_RM1,
  A.FK_PREVENTA,
  A.FK_LANZAMIENTO,
  A.FK_SKU,
  A.MV_PERIODO_INICIO_R,
  A.MV_PERIODO_FIN_R,
  A.MV_MES,
  SUM(A.MD_COBERTURA),
  SUM(A.MD_RECOMPRA)
FROM MKT_LZ_FACT_OBJ_SKU_PVTA_COB A, MKT_LZ_COB_ETL_AGG1 B
WHERE
A.FK_PERIODO_FIN=B.FK_PERIODO_FIN
AND A.FK_ESTADO=B.FK_ESTADO
AND A.FK_REGION=B.FK_REGION
AND A.FK_PREVENTA=B.FK_PREVENTA
AND A.FK_CANAL_RM1=B.FK_CANAL_RM1
AND A.FK_LANZAMIENTO=B.FK_LANZAMIENTO
AND A.FK_SKU=B.FK_SKU
AND NVL(A.MV_PERIODO_INICIO_R,'0')=NVL(B.MV_PERIODO_INICIO_R,'0')
AND NVL(A.MV_PERIODO_FIN_R,'0')=NVL(B.MV_PERIODO_FIN_R,'0')
AND NVL(A.MV_MES,'0')=NVL(B.MV_MES,'0')
group by
A.FK_PERIODO_FIN, A.FK_ESTADO, A.FK_REGION, A.FK_CANAL_RM1, A.FK_LANZAMIENTO, 
A.FK_SKU, A.MV_PERIODO_INICIO_R, A.MV_PERIODO_FIN_R, A.MV_MES, A.FK_PERIODO_INICIO, 
A.FK_PREVENTA);
COMMIT;

-- TABLA AGREGADA POR ESTADO

INSERT INTO MKT_LZ_AGG_SKU_PVTA_COB_EDO(
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Tradicional' AND  ROWNUM =1) AS TIPO_PREVENTA,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERUTRA_TRADICIONAL,
OB.RECOMPRA_TRA
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.ESTADO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='ESTADO'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Especializada' AND  ROWNUM =1) AS TIPO_PREVENTA,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_ESPECIALIZADA,
OB.RECOMPRA_ESP
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.ESTADO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND L.GV_CLAVE_LANZAMIENTO=OB.CLAVE_LANZAMIENTO
AND OB.CORTE='ESTADO'
AND OB.TIPO_ENTRADA='SKU');


--WHERE ESTADO IN (SELECT ESTADO FROM MKT_GEOGRAFIA)
-- TABLA TEMPORAL DE COMBINACIONES PARA INSERTAR 
CREATE TABLE MKT_LZ_COB_ETL_AGG2 AS(
SELECT FK_PERIODO_INICIO,
  FK_PERIODO_FIN,
  FK_ESTADO,
  FK_CANAL_RM1,
  FK_PREVENTA,
  FK_LANZAMIENTO,
  FK_SKU,
  MV_PERIODO_INICIO_R,
  MV_PERIODO_FIN_R,
  MV_MES
 FROM MKT_LZ_AGG_SKU_PVTA_COB_REG 
  MINUS
SELECT FK_PERIODO_INICIO,
  FK_PERIODO_FIN,
  FK_ESTADO,
  FK_CANAL_RM1,
  FK_PREVENTA,
  FK_LANZAMIENTO,
  FK_SKU,
  MV_PERIODO_INICIO_R,
  MV_PERIODO_FIN_R,
  MV_MES
 FROM MKT_LZ_AGG_SKU_PVTA_COB_EDO) ;
 COMMIT;
 
-- COMPARANDO E INSERTANDO REGISTROS 
INSERT INTO MKT_LZ_AGG_SKU_PVTA_COB_EDO(
 SELECT A.FK_PERIODO_INICIO,
  A.FK_PERIODO_FIN,
  A.FK_ESTADO,
  A.FK_CANAL_RM1,
  A.FK_PREVENTA,
  A.FK_LANZAMIENTO,
  A.FK_SKU,
  A.MV_PERIODO_INICIO_R,
  A.MV_PERIODO_FIN_R,
  A.MV_MES,
  SUM(A.MD_COBERTURA),
  SUM(A.MD_RECOMPRA)
FROM MKT_LZ_AGG_SKU_PVTA_COB_REG A, MKT_LZ_COB_ETL_AGG1 B
WHERE
A.FK_PERIODO_FIN=B.FK_PERIODO_FIN
AND A.FK_ESTADO=B.FK_ESTADO
AND A.FK_REGION=B.FK_REGION
AND A.FK_PREVENTA=B.FK_PREVENTA
AND A.FK_CANAL_RM1=B.FK_CANAL_RM1
AND A.FK_LANZAMIENTO=B.FK_LANZAMIENTO
AND A.FK_SKU=B.FK_SKU
AND NVL(A.MV_PERIODO_INICIO_R,'0')=NVL(B.MV_PERIODO_INICIO_R,'0')
AND NVL(A.MV_PERIODO_FIN_R,'0')=NVL(B.MV_PERIODO_FIN_R,'0')
AND NVL(A.MV_MES,'0')=NVL(B.MV_MES,'0')
group by
A.FK_PERIODO_FIN, A.FK_ESTADO, A.FK_CANAL_RM1, A.FK_LANZAMIENTO, 
A.FK_SKU, A.MV_PERIODO_INICIO_R, A.MV_PERIODO_FIN_R, A.MV_MES, A.FK_PERIODO_INICIO, 
A.FK_PREVENTA);



DROP TABLE MKT_LZ_COB_ETL_AGG1;
DROP TABLE MKT_LZ_COB_ETL_AGG2;
COMMIT;




-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
----------------------- LLENADO DE TABLA DE HECHOS PARA OBJETIVOS DE COBERTURA POR SKU  PREVENTA Y GEC ----------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------

--TABLA DE HECHOS A CENTRO
--SELECT * FROM MKT_ST_LZ_OBJETIVO;


-- -- LLENADO DE TABLA AGREGADA POR REGION PARA OBJETIVOS DE COBERTURA POR SKU, PREVENTA Y GEC
INSERT INTO MKT_LZ_FACT_OBJ_SKU_VPT_GEC_CB(
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
G.REGION_ZONA,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Tradicional' AND  ROWNUM =1) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='ORO') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_ORO_TRA
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.CENTRO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='UNIDAD OPERATIVA'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
G.REGION_ZONA,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Tradicional' AND  ROWNUM =1) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='PLATA') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_PLATA_TRA
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.CENTRO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='UNIDAD OPERATIVA'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
G.REGION_ZONA,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Tradicional' AND  ROWNUM =1) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='BRONCE') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_BRONCE_TRA
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.CENTRO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='UNIDAD OPERATIVA'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
G.REGION_ZONA,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Especializada' AND  ROWNUM =1) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='ORO') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_ORO_ESP
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.CENTRO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='UNIDAD OPERATIVA'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
G.REGION_ZONA,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Especializada' AND  ROWNUM =1) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='PLATA') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_PLATA_ESP
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.CENTRO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='UNIDAD OPERATIVA'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
G.REGION_ZONA,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Especializada' AND  ROWNUM =1) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='BRONCE') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_BRONCE_ESP
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.CENTRO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='UNIDAD OPERATIVA'
AND OB.TIPO_ENTRADA='SKU'
);


-----------------------------------------------------------------------
--------------------------------------------------------------------------
-------------------------------------------------------------------------

INSERT INTO MKT_LZ_AGG_SKU_VPT_GEC_COB_REG(
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Tradicional' AND  ROWNUM =1) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='ORO') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_ORO_TRA
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.REGION_ZONA=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='REGION'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Tradicional' AND  ROWNUM <2) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='PLATA') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_PLATA_TRA
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.REGION_ZONA=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='REGION'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Tradicional' AND  ROWNUM =1) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='BRONCE') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_BRONCE_TRA
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.REGION_ZONA=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='REGION'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Especializada' AND  ROWNUM =1) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='ORO') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_ORO_ESP
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.REGION_ZONA=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='REGION'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Especializada' AND  ROWNUM =1) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='PLATA') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_PLATA_ESP
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.REGION_ZONA=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='REGION'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
G.ESTADO,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Especializada' AND  ROWNUM =1) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='BRONCE') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_BRONCE_ESP
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.REGION_ZONA=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='REGION'
AND OB.TIPO_ENTRADA='SKU');
COMMIT;

--WHERE ESTADO IN (SELECT ESTADO FROM MKT_GEOGRAFIA)
-- TABLA TEMPORAL DE COMBINACIONES PARA INSERTAR 
CREATE TABLE MKT_LZ_COB_ETL_AGG1 AS(
SELECT FK_PERIODO_INICIO,
  FK_PERIODO_FIN,
  FK_ESTADO,
  FK_REGION,
  FK_CANAL_RM1,
  FK_PREVENTA,
  FK_GEC,
  FK_LANZAMIENTO,
  FK_SKU,
  MV_PERIODO_INICIO_R,
  MV_PERIODO_FIN_R,
  MV_MES
 FROM MKT_LZ_FACT_OBJ_SKU_VPT_GEC_CB 
  MINUS
SELECT FK_PERIODO_INICIO,
  FK_PERIODO_FIN,
  FK_ESTADO,
  FK_REGION,
  FK_CANAL_RM1,
  FK_PREVENTA,
  FK_GEC,
  FK_LANZAMIENTO,
  FK_SKU,
  MV_PERIODO_INICIO_R,
  MV_PERIODO_FIN_R,
  MV_MES
 FROM MKT_LZ_AGG_SKU_VPT_GEC_COB_REG) ;
 COMMIT;
 
-- COMPARANDO E INSERTANDO REGISTROS 
CREATE TABLE TA AS(
 SELECT DISTINCT A.FK_PERIODO_INICIO,
  A.FK_PERIODO_FIN,
  A.FK_ESTADO,
  A.FK_REGION,
  A.FK_CANAL_RM1,
  A.FK_PREVENTA,
  A.FK_GEC,
  A.FK_LANZAMIENTO,
  A.FK_SKU,
  A.MV_PERIODO_INICIO_R,
  A.MV_PERIODO_FIN_R,
  A.MV_MES,
  SUM(A.MD_COBERTURA) AS MD_COBERTURA 
FROM MKT_LZ_FACT_OBJ_SKU_VPT_GEC_CB A, MKT_LZ_COB_ETL_AGG1 B
WHERE
A.FK_PERIODO_FIN=B.FK_PERIODO_FIN
AND A.FK_ESTADO=B.FK_ESTADO
AND A.FK_REGION=B.FK_REGION
AND A.FK_PREVENTA=B.FK_PREVENTA
AND A.FK_CANAL_RM1=B.FK_CANAL_RM1
AND A.FK_LANZAMIENTO=B.FK_LANZAMIENTO
AND A.FK_SKU=B.FK_SKU
AND NVL(A.MV_PERIODO_INICIO_R,'0')=NVL(B.MV_PERIODO_INICIO_R,'0')
AND NVL(A.MV_PERIODO_FIN_R,'0')=NVL(B.MV_PERIODO_FIN_R,'0')
AND NVL(A.MV_MES,'0')=NVL(B.MV_MES,'0')
group by
A.FK_PERIODO_FIN, A.FK_ESTADO, A.FK_REGION, A.FK_CANAL_RM1, A.FK_LANZAMIENTO, 
A.FK_SKU, A.MV_PERIODO_INICIO_R, A.MV_PERIODO_FIN_R, A.FK_GEC, A.MV_MES, 
A.FK_PERIODO_INICIO, A.FK_PREVENTA);

INSERT INTO MKT_LZ_AGG_SKU_VPT_GEC_COB_REG(
SELECT * FROM TA);

DROP TABLE TA;
DROP TABLE MKT_LZ_COB_ETL_AGG1;
--DROP TABLE MKT_LZ_COB_ETL_AGG2;

COMMIT;

-- TABLA AGREGADA POR ESTADO
-----------------------------------------------------------------------
--------------------------------------------------------------------------
-------------------------------------------------------------------------

INSERT INTO MKT_LZ_AGG_SKU_VPT_GEC_COB_EDO(
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Tradicional' AND  ROWNUM =1) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='ORO') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_ORO_TRA
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.ESTADO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='ESTADO'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Tradicional' AND  ROWNUM =1) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='PLATA') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_PLATA_TRA
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.ESTADO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='ESTADO'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Tradicional' AND  ROWNUM =1) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='BRONCE') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_BRONCE_TRA
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.ESTADO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='ESTADO'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Especializada' AND  ROWNUM =1) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='ORO') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_ORO_ESP
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.ESTADO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='ESTADO'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Especializada' AND  ROWNUM =1) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='PLATA') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_PLATA_ESP
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.ESTADO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='ESTADO'
AND OB.TIPO_ENTRADA='SKU'
UNION
SELECT DISTINCT TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_INI_TOTAL),'YYYYMM')) AS PERIODO_INICIO,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_TOTAL),'YYYYMM')) AS PERIODO_FIN,
OB.CLAVE_CORTE,
OB.CANAL,
(SELECT P.PK_PREVENTA FROM MKT_LZ_DIM_TIPO_PREVENTA P
WHERE P.GV_PREVENTA='Especializada' AND  ROWNUM =1) AS TIPO_PREVENTA,
(SELECT G.CLAVE_GEC FROM MKT_GEC G
WHERE G.GEC='BRONCE') AS GEC,
L.PK_LANZAMIENTO,
LPAD(OB.ID_ENTRADA,18,'0') AS SKU,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FEHCA_INI_REAL),'YYYYMM')) AS PIR,
TO_NUMBER(TO_CHAR(TO_DATE(OB.FECHA_FIN_REAL),'YYYYMM')) AS PIF,
OB.MES,
OB.COBERTURA_BRONCE_ESP
FROM MKT_ST_LZ_OBJETIVO OB, MKT_GEOGRAFIA G, MKT_LZ_DIM_LANZAMIENTO L
WHERE G.ESTADO=OB.CLAVE_CORTE
AND L.GV_CONSECUTIVO=OB.CONSECUTIVO
AND L.GV_NOMBRE_LANZAMIENTO=OB.NOMBRE_LANZAMIENTO
AND NVL(L.GV_CLAVE_LANZAMIENTO,'#')=NVL(OB.CLAVE_LANZAMIENTO,'#')
AND OB.CORTE='ESTADO'
AND OB.TIPO_ENTRADA='SKU');
COMMIT;
--HOLA
--WHERE ESTADO IN (SELECT ESTADO FROM MKT_GEOGRAFIA)
-- TABLA TEMPORAL DE COMBINACIONES PARA INSERTAR 
CREATE TABLE MKT_LZ_COB_ETL_AGG1 AS(
SELECT FK_PERIODO_INICIO,
  FK_PERIODO_FIN,
  FK_ESTADO,
  FK_CANAL_RM1,
  FK_PREVENTA,
  FK_GEC,
  FK_LANZAMIENTO,
  FK_SKU,
  MV_PERIODO_INICIO_R,
  MV_PERIODO_FIN_R,
  MV_MES
 FROM MKT_LZ_AGG_SKU_VPT_GEC_COB_REG 
  MINUS
SELECT FK_PERIODO_INICIO,
  FK_PERIODO_FIN,
  FK_ESTADO,
  FK_CANAL_RM1,
  FK_PREVENTA,
  FK_GEC,
  FK_LANZAMIENTO,
  FK_SKU,
  MV_PERIODO_INICIO_R,
  MV_PERIODO_FIN_R,
  MV_MES
 FROM MKT_LZ_AGG_SKU_VPT_GEC_COB_EDO) ;
 COMMIT;
 
-- COMPARANDO E INSERTANDO REGISTROS 
CREATE TABLE TA AS(
 SELECT DISTINCT A.FK_PERIODO_INICIO,
  A.FK_PERIODO_FIN,
  A.FK_ESTADO,
  A.FK_CANAL_RM1,
  A.FK_PREVENTA,
  A.FK_GEC,
  A.FK_LANZAMIENTO,
  A.FK_SKU,
  A.MV_PERIODO_INICIO_R,
  A.MV_PERIODO_FIN_R,
  A.MV_MES,
  SUM(A.MD_COBERTURA) AS MD_COBERTURA 
FROM MKT_LZ_FACT_OBJ_SKU_VPT_GEC_CB A, MKT_LZ_COB_ETL_AGG1 B
WHERE
A.FK_PERIODO_FIN=B.FK_PERIODO_FIN
AND A.FK_ESTADO=B.FK_ESTADO
AND A.FK_PREVENTA=B.FK_PREVENTA
AND A.FK_CANAL_RM1=B.FK_CANAL_RM1
AND A.FK_LANZAMIENTO=B.FK_LANZAMIENTO
AND A.FK_SKU=B.FK_SKU
AND NVL(A.MV_PERIODO_INICIO_R,'0')=NVL(B.MV_PERIODO_INICIO_R,'0')
AND NVL(A.MV_PERIODO_FIN_R,'0')=NVL(B.MV_PERIODO_FIN_R,'0')
AND NVL(A.MV_MES,'0')=NVL(B.MV_MES,'0')
group by
A.FK_PERIODO_FIN, A.FK_ESTADO, A.FK_CANAL_RM1, A.FK_LANZAMIENTO, 
A.FK_SKU, A.MV_PERIODO_INICIO_R, A.MV_PERIODO_FIN_R, A.FK_GEC, A.MV_MES, 
A.FK_PERIODO_INICIO, A.FK_PREVENTA);

INSERT INTO MKT_LZ_AGG_SKU_VPT_GEC_COB_EDO(
SELECT * FROM TA);

DROP TABLE TA;
COMMIT;

DROP TABLE MKT_LZ_COB_ETL_AGG1;
--DROP TABLE MKT_LZ_COB_ETL_AGG2;
COMMIT;