-- DLL ESTRELLA Y DIMENSIONES PROMOCIONES Y SAMPLINGS 

---ELIMINACION DE TABLAS

DROP TABLE MKT_PS_FACT_COB_GEC_SKU;
DROP TABLE MKT_PS_FACT_COB_GEC_PEP;
DROP TABLE MKT_PS_FACT_COB_SKU;
DROP TABLE MKT_PS_FACT_COB_PEP;
DROP TABLE MKT_PS_FACT_VTA_SKU_PV;
DROP TABLE MKT_PS_FACT_VTA_PEP_PV;
DROP TABLE MKT_PS_FACT_VTA_SKU;
DROP TABLE MKT_PS_FACT_VTA_PEP;
DROP TABLE MKT_PS_AGG_COB_GEC_SKU_REG;
DROP TABLE MKT_PS_AGG_COB_GEC_PEP_REG;
DROP TABLE MKT_PS_AGG_COB_SKU_REG;
DROP TABLE MKT_PS_AGG_COB_PEP_REG;
DROP TABLE MKT_PS_AGG_VTA_SKU_PV_REG;
DROP TABLE MKT_PS_AGG_VTA_PEP_PV_REG;
DROP TABLE MKT_PS_AGG_VTA_SKU_REG;
DROP TABLE MKT_PS_AGG_VTA_PEP_REG;
DROP TABLE MKT_PS_AGG_COB_GEC_SKU_EDO;
DROP TABLE MKT_PS_AGG_COB_GEC_PEP_EDO;
DROP TABLE MKT_PS_AGG_COB_SKU_EDO;
DROP TABLE MKT_PS_AGG_COB_PEP_EDO;
DROP TABLE MKT_PS_AGG_VTA_SKU_PV_EDO;
DROP TABLE MKT_PS_AGG_VTA_PEP_PV_EDO;
DROP TABLE MKT_PS_AGG_VTA_SKU_EDO;
DROP TABLE MKT_PS_AGG_VTA_PEP_EDO;
DROP TABLE MKT_PS_FACT_MB51;
DROP TABLE MKT_PS_FACT_MB58;

DROP TABLE MKT_PS_DIM_CANAL_MKT;
DROP TABLE MKT_PS_DIM_USUARIO_MB51;
DROP TABLE MKT_PS_DIM_ALMACEN_MB51;
DROP TABLE MKT_PS_DIM_REFERENCIA_MB51;
DROP TABLE MKT_PS_DIM_MATERIAL_MB51;
DROP TABLE MKT_PS_DIM_DOC_MATERIAL_MB51;
DROP TABLE MKT_PS_DIM_PEDIDO_MB51;
DROP TABLE MKT_PS_DIM_PROMOCION;
DROP TABLE MKT_PS_DIM_TIPO_PROMOCION;

COMMIT;


-- DIMENSIONES 


-- DIMENSIONES COMPARTIDAS

-- TIPO PREVENTA 

-- DIMENSION DE PROMOCION 

CREATE TABLE MKT_PS_DIM_PROMOCION(
PK_PROMOCION NUMBER(10,0) NOT NULL PRIMARY KEY,
GV_NOMBRE_PROMOCION	NVARCHAR2(50)
);



-- DIMENSION TIPO DE PROMOCION 

CREATE TABLE MKT_PS_DIM_TIPO_PROMOCION(
PK_TIPO_PROMOCION NUMBER(10,0) NOT NULL PRIMARY KEY
);


--DIMENSION DE CANAL MKT POR RUTA DE REPARTO 


CREATE TABLE MKT_PS_DIM_CANAL_MKT(
PK_CANAL_MKT	NUMBER(10,0) NOT NULL PRIMARY KEY,
GV_CANAL_MKT	NVARCHAR2(20),
GV_RUTA_REPARTO	NVARCHAR2(6)
);





-- DIMENSION USUARIO DE LA TRANSACCION MB51

CREATE TABLE MKT_PS_DIM_USUARIO_MB51(
PK_USUARIO NUMBER(10,0) NOT NULL PRIMARY KEY,
GV_USUARIO NVARCHAR2(10)
);


--DIMENSION DE ALMACEN MB51

CREATE TABLE MKT_PS_DIM_ALMACEN_MB51(
PK_ALMACEN NUMBER(10,0) NOT NULL PRIMARY KEY,
GV_ALMACEN NVARCHAR2(10)
);


-- DIMENSION REFERENCIA MB51

CREATE TABLE MKT_PS_DIM_REFERENCIA_MB51(
PK_REFERENCIA NUMBER(10,0) NOT NULL PRIMARY KEY,
FK_REFERENCIA NVARCHAR2(30)
);	


-- DIMENSION MATERIAL MB51

CREATE TABLE MKT_PS_DIM_MATERIAL_MB51(
PK_MATERIAL NUMBER(10,0) NOT NULL PRIMARY KEY,
GV_CLAVE_MATERIAL NVARCHAR2(18),
GV_DESC_MATERIAL NVARCHAR2(50),
GV_UME NVARCHAR2(3)
);


-- DIMENSION DOCUMENTO DE MATERIAL MB51


CREATE TABLE MKT_PS_DIM_DOC_MATERIAL_MB51(
PK_DOC_MATERIAL NUMBER(10,0) NOT NULL PRIMARY KEY,
GV_DOC_MAERIAL NVARCHAR2(10)
);


--DIMENSION  PEDIDO MB51

CREATE TABLE MKT_PS_DIM_PEDIDO_MB51(
PK_PEDIDO NUMBER(10,0) NOT NULL PRIMARY KEY,
GV_PEDIDO NVARCHAR2(10)
);



---------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------
-----------------------------------------------TABLAS DE HECHOS PROMOCIONES Y SAMPLINGS------------------------------
---------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------

-- TABLA DE HECHOS OBJETIVOS DE COBERTURAS GEC SKU 
--SE AGREGO CENTRO
CREATE TABLE MKT_PS_FACT_COB_GEC_SKU(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CENTRO NVARCHAR2(6),
--FK_UO NVARCHAR2(6),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_GEC NVARCHAR2(3),
FK_SKU NVARCHAR2(18),
MD_CLIENTES NUMBER(10,2),
MD_COBERTURA NUMBER(10,2)
);


ALTER TABLE MKT_PS_FACT_COB_GEC_SKU
ADD CONSTRAINT MKT_PS_FACT_COB_GEC_SKU_P
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_PS_FACT_COB_GEC_SKU
ADD CONSTRAINT MKT_PS_FACT_COB_GEC_SKU_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);


ALTER TABLE MKT_PS_FACT_COB_GEC_SKU
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CENTRO,
--FK_UO,
FK_CANAL_RM1,
--FK_CATEGORIA,
--FK_RETORNABILIDAD,
--FK_EMPAQUE,
--FK_TAMANO,
FK_PREVENTA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_GEC,
FK_SKU
);


-- TABLA DE HECHOS OBJETIVOS DE COBERTURAS GEC PEP 
-- SE AGREGO CENTRO
CREATE TABLE MKT_PS_FACT_COB_GEC_PEP(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CENTRO NVARCHAR2(6),
--FK_UO NVARCHAR2(6),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_GEC NVARCHAR2(3),
FK_PEP NVARCHAR2(22),
MD_CLIENTES NUMBER(10,2),
MD_COBERTURA NUMBER(10,2)
);


ALTER TABLE MKT_PS_FACT_COB_GEC_PEP
ADD CONSTRAINT MKT_PS_FACT_COB_GEC_PEP_P
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_PS_FACT_COB_GEC_PEP
ADD CONSTRAINT MKT_PS_FACT_COB_GEC_PEP_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);

ALTER TABLE MKT_PS_FACT_COB_GEC_PEP
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CENTRO,
--FK_UO,
FK_CANAL_RM1,
FK_PREVENTA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_GEC,
FK_PEP
);
-----------
-----------
-----------
-----------



-- TABLA DE HECHOS OBJETIVOS DE COBERTURAS SKU 

CREATE TABLE MKT_PS_FACT_COB_SKU(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CENTRO NVARCHAR2(6),
--FK_UO NVARCHAR2(6),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MD_CLIENTES NUMBER(10,2),
MD_COBERTURA NUMBER(10,2)
);


ALTER TABLE MKT_PS_FACT_COB_SKU
ADD CONSTRAINT MKT_PS_FACT_COB_SKU_P
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_PS_FACT_COB_SKU
ADD CONSTRAINT MKT_PS_FACT_COB_GEC_SKU_PR2
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);

ALTER TABLE MKT_PS_FACT_COB_SKU
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CENTRO,
--FK_UO,
FK_CANAL_RM1,
FK_PREVENTA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_SKU
);


-- TABLA DE HECHOS OBJETIVOS DE COBERTURAS GEC PEP 

CREATE TABLE MKT_PS_FACT_COB_PEP(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CENTRO NVARCHAR2(6),
--FK_UO NVARCHAR2(6),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
--FK_GEC NVARCHAR2(3), --********************
FK_PEP NVARCHAR2(22),
MD_CLIENTES NUMBER(10,2),
MD_COBERTURA NUMBER(10,2)
);


ALTER TABLE MKT_PS_FACT_COB_PEP
ADD CONSTRAINT MKT_PS_FACT_COB_GEC_PEP_PP
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_PS_FACT_COB_PEP
ADD CONSTRAINT MKT_PS_FACT_COB_GEC_PEP_PR2
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);

ALTER TABLE MKT_PS_FACT_COB_PEP
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CENTRO,
--FK_UO,
FK_CANAL_RM1,
FK_PREVENTA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_PEP
);



-------------------------
-------------------------
------------------------
-- TABLA DE HECHOS DE INDICADORES DE VENTAS SKU


CREATE TABLE MKT_PS_FACT_VTA_SKU_PV(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CENTRO NVARCHAR2(6),
--FK_UO NVARCHAR2(6),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PLAN_VISITA NVARCHAR2(3),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MD_CF_OBJ NUMBER(10,2),
MD_CFC_OBJ NUMBER(10,2),
MD_CU_OBJ NUMBER(10,2),
MD_PIEZAS_OBJ NUMBER(10,2),
MD_REDENCION NUMBER(10,2),
MD_DESCUENTO NUMBER(10,2),
MD_CF_CONV NUMBER(10,2),
MD_PIEZAS_CONV NUMBER(10,2),
MD_CF_REAL NUMBER(10,2)
);

ALTER TABLE MKT_PS_FACT_VTA_SKU_PV
ADD CONSTRAINT MKT_PS_FACT_VTA_SKU_PV_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);


ALTER TABLE MKT_PS_FACT_VTA_SKU_PV
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CENTRO,
--FK_UO,
FK_CANAL_RM1,
FK_PLAN_VISITA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_SKU
);


-- TABLA DE HECHOS DE INDICADORES DE VENTAS PEP


CREATE TABLE MKT_PS_FACT_VTA_PEP_PV(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CENTRO NVARCHAR2(6),
--FK_UO NVARCHAR2(6),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PLAN_VISITA NVARCHAR2(3),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_PEP NVARCHAR2(22),
MD_CF_OBJ NUMBER(10,2),
MD_CFC_OBJ NUMBER(10,2),
MD_CU_OBJ NUMBER(10,2),
MD_PIEZAS_OBJ NUMBER(10,2),
MD_REDENCION NUMBER(10,2),
MD_DESCUENTO NUMBER(10,2),
MD_CF_CONV NUMBER(10,2),
MD_PIEZAS_CONV NUMBER(10,2),
MD_CF_REAL NUMBER(10,2)
);

ALTER TABLE MKT_PS_FACT_VTA_PEP_PV
ADD CONSTRAINT MKT_PS_FACT_VTA_PEP_PV_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);


ALTER TABLE MKT_PS_FACT_VTA_PEP_PV
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CENTRO,
--FK_UO,
FK_CANAL_RM1,
FK_PLAN_VISITA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_PEP
);


-------------------------
-------------------------
------------------------
-- TABLA DE HECHOS DE INDICADORES DE VENTAS SKU


CREATE TABLE MKT_PS_FACT_VTA_SKU(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CENTRO NVARCHAR2(6),
--FK_UO NVARCHAR2(6),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MD_CF_OBJ NUMBER(10,2),
MD_CFC_OBJ NUMBER(10,2),
MD_CU_OBJ NUMBER(10,2),
MD_PIEZAS_OBJ NUMBER(10,2),
MD_REDENCION NUMBER(10,2),
MD_DESCUENTO NUMBER(10,2),
MD_CF_CONV NUMBER(10,2),
MD_PIEZAS_CONV NUMBER(10,2),
MD_CF_REAL NUMBER(10,2),
MD_GENERICO_1 NUMBER(10,2),
MD_GENERICO_2 NUMBER(10,2),
MD_GENERICO_3 NUMBER(10,2),
MD_GENERICO_4 NUMBER(10,2),
MD_GENERICO_5 NUMBER(10,2),
MD_GENERICO_6 NUMBER(10,2),
MD_GENERICO_7 NUMBER(10,2),
MD_GENERICO_8 NUMBER(10,2),
MD_GENERICO_9 NUMBER(10,2),
MD_GENERICO_10 NUMBER(10,2)
);

ALTER TABLE MKT_PS_FACT_VTA_SKU
ADD CONSTRAINT MKT_PS_FACT_VTA_SKU_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);


ALTER TABLE MKT_PS_FACT_VTA_SKU
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CENTRO,
--FK_UO,
FK_CANAL_RM1,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_SKU
);


-- TABLA DE HECHOS DE INDICADORES DE VENTAS PEP


CREATE TABLE MKT_PS_FACT_VTA_PEP(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CENTRO NVARCHAR2(6),
--FK_UO NVARCHAR2(6),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_PEP NVARCHAR2(22),
MD_CF_OBJ NUMBER(10,2),
MD_CFC_OBJ NUMBER(10,2),
MD_CU_OBJ NUMBER(10,2),
MD_PIEZAS_OBJ NUMBER(10,2),
MD_REDENCION NUMBER(10,2),
MD_DESCUENTO NUMBER(10,2),
MD_CF_CONV NUMBER(10,2),
MD_PIEZAS_CONV NUMBER(10,2),
MD_CF_REAL NUMBER(10,2),
MD_GENERICO_1 NUMBER(10,2),
MD_GENERICO_2 NUMBER(10,2),
MD_GENERICO_3 NUMBER(10,2),
MD_GENERICO_4 NUMBER(10,2),
MD_GENERICO_5 NUMBER(10,2),
MD_GENERICO_6 NUMBER(10,2),
MD_GENERICO_7 NUMBER(10,2),
MD_GENERICO_8 NUMBER(10,2),
MD_GENERICO_9 NUMBER(10,2),
MD_GENERICO_10 NUMBER(10,2)
);

ALTER TABLE MKT_PS_FACT_VTA_PEP
ADD CONSTRAINT MKT_PS_FACT_VTA_PEP_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);


ALTER TABLE MKT_PS_FACT_VTA_PEP
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CENTRO,
--FK_UO,
FK_CANAL_RM1,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_PEP
);


--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
-----------------------------------TABLAS DE HECHOS AGG A REGION----------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------


-- TABLA DE HECHOS OBJETIVOS DE COBERTURAS GEC SKU 

CREATE TABLE MKT_PS_AGG_COB_GEC_SKU_REG(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_GEC NVARCHAR2(3),
FK_SKU NVARCHAR2(18),
MD_CLIENTES NUMBER(10,2),
MD_COBERTURA NUMBER(10,2)
);


ALTER TABLE MKT_PS_AGG_COB_GEC_SKU_REG
ADD CONSTRAINT MKT_PS_AGG_COB_GEC_SKU_REG_P
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_PS_AGG_COB_GEC_SKU_REG
ADD CONSTRAINT MKT_PS_AGG_COB_GEC_SKU_REG_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);

ALTER TABLE MKT_PS_AGG_COB_GEC_SKU_REG
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CANAL_RM1,
FK_PREVENTA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_GEC,
FK_SKU
);


-- TABLA DE HECHOS OBJETIVOS DE COBERTURAS GEC PEP 

CREATE TABLE MKT_PS_AGG_COB_GEC_PEP_REG(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_GEC NVARCHAR2(3),
FK_PEP NVARCHAR2(22),
MD_CLIENTES NUMBER(10,2),
MD_COBERTURA NUMBER(10,2)
);


ALTER TABLE MKT_PS_AGG_COB_GEC_PEP_REG
ADD CONSTRAINT MKT_PS_AGG_COB_GEC_PEP_REG_P
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_PS_AGG_COB_GEC_PEP_REG
ADD CONSTRAINT MKT_PS_AGG_COB_GEC_PEP_REG_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);

ALTER TABLE MKT_PS_AGG_COB_GEC_PEP_REG
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CANAL_RM1,
FK_PREVENTA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_GEC,
FK_PEP
);
-----------
-----------
-----------
-----------



-- TABLA DE HECHOS OBJETIVOS DE COBERTURAS SKU 

CREATE TABLE MKT_PS_AGG_COB_SKU_REG(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MD_CLIENTES NUMBER(10,2),
MD_COBERTURA NUMBER(10,2)
);


ALTER TABLE MKT_PS_AGG_COB_SKU_REG
ADD CONSTRAINT MKT_PS_AGG_COB_SKU_REG_P
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_PS_AGG_COB_SKU_REG
ADD CONSTRAINT MKT_PS_AGG_COB_SKU_REG_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);

ALTER TABLE MKT_PS_AGG_COB_SKU_REG
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CANAL_RM1,
FK_PREVENTA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_SKU
);


-- TABLA DE HECHOS OBJETIVOS DE COBERTURAS GEC PEP 

CREATE TABLE MKT_PS_AGG_COB_PEP_REG(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
--FK_GEC NVARCHAR2(3),--********************
FK_PEP NVARCHAR2(22),
MD_CLIENTES NUMBER(10,2),
MD_COBERTURA NUMBER(10,2)
);


ALTER TABLE MKT_PS_AGG_COB_PEP_REG
ADD CONSTRAINT MKT_PS_AGG_COB_PEP_REG_P
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_PS_AGG_COB_PEP_REG
ADD CONSTRAINT MKT_PS_AGG_COB_PEP_REG_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);

ALTER TABLE MKT_PS_AGG_COB_PEP_REG
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CANAL_RM1,
FK_PREVENTA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_PEP
);



-------------------------
-------------------------
------------------------
-- TABLA DE HECHOS DE INDICADORES DE VENTAS SKU


CREATE TABLE MKT_PS_AGG_VTA_SKU_PV_REG(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PLAN_VISITA NVARCHAR2(3),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MD_CF_OBJ NUMBER(10,2),
MD_CFC_OBJ NUMBER(10,2),
MD_CU_OBJ NUMBER(10,2),
MD_PIEZAS_OBJ NUMBER(10,2),
MD_REDENCION NUMBER(10,2),
MD_DESCUENTO NUMBER(10,2),
MD_CF_CONV NUMBER(10,2),
MD_PIEZAS_CONV NUMBER(10,2),
MD_CF_REAL NUMBER(10,2)
);

ALTER TABLE MKT_PS_AGG_VTA_SKU_PV_REG
ADD CONSTRAINT MKT_PS_AGG_VTA_SKU_PV_REG_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);


ALTER TABLE MKT_PS_AGG_VTA_SKU_PV_REG
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CANAL_RM1,
FK_PLAN_VISITA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_SKU
);


-- TABLA DE HECHOS DE INDICADORES DE VENTAS PEP


CREATE TABLE MKT_PS_AGG_VTA_PEP_PV_REG(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PLAN_VISITA NVARCHAR2(3),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_PEP NVARCHAR2(22),
MD_CF_OBJ NUMBER(10,2),
MD_CFC_OBJ NUMBER(10,2),
MD_CU_OBJ NUMBER(10,2),
MD_PIEZAS_OBJ NUMBER(10,2),
MD_REDENCION NUMBER(10,2),
MD_DESCUENTO NUMBER(10,2),
MD_CF_CONV NUMBER(10,2),
MD_PIEZAS_CONV NUMBER(10,2),
MD_CF_REAL NUMBER(10,2)
);

ALTER TABLE MKT_PS_AGG_VTA_PEP_PV_REG
ADD CONSTRAINT MKT_PS_AGG_VTA_PEP_PV_REG_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);


ALTER TABLE MKT_PS_AGG_VTA_PEP_PV_REG
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CANAL_RM1,
FK_PLAN_VISITA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_PEP
);


-------------------------
-------------------------
------------------------
-- TABLA DE HECHOS DE INDICADORES DE VENTAS SKU


CREATE TABLE MKT_PS_AGG_VTA_SKU_REG(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MD_CF_OBJ NUMBER(10,2),
MD_CFC_OBJ NUMBER(10,2),
MD_CU_OBJ NUMBER(10,2),
MD_PIEZAS_OBJ NUMBER(10,2),
MD_REDENCION NUMBER(10,2),
MD_DESCUENTO NUMBER(10,2),
MD_CF_CONV NUMBER(10,2),
MD_PIEZAS_CONV NUMBER(10,2),
MD_CF_REAL NUMBER(10,2),
MD_GENERICO_1 NUMBER(10,2),
MD_GENERICO_2 NUMBER(10,2),
MD_GENERICO_3 NUMBER(10,2),
MD_GENERICO_4 NUMBER(10,2),
MD_GENERICO_5 NUMBER(10,2),
MD_GENERICO_6 NUMBER(10,2),
MD_GENERICO_7 NUMBER(10,2),
MD_GENERICO_8 NUMBER(10,2),
MD_GENERICO_9 NUMBER(10,2),
MD_GENERICO_10 NUMBER(10,2)
);

ALTER TABLE MKT_PS_AGG_VTA_SKU_REG
ADD CONSTRAINT MKT_PS_AGG_VTA_SKU_REG_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);


ALTER TABLE MKT_PS_AGG_VTA_SKU_REG
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CANAL_RM1,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_SKU
);


-- TABLA DE HECHOS DE INDICADORES DE VENTAS PEP


CREATE TABLE MKT_PS_AGG_VTA_PEP_REG(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_PEP NVARCHAR2(22),
MD_CF_OBJ NUMBER(10,2),
MD_CFC_OBJ NUMBER(10,2),
MD_CU_OBJ NUMBER(10,2),
MD_PIEZAS_OBJ NUMBER(10,2),
MD_REDENCION NUMBER(10,2),
MD_DESCUENTO NUMBER(10,2),
MD_CF_CONV NUMBER(10,2),
MD_PIEZAS_CONV NUMBER(10,2),
MD_CF_REAL NUMBER(10,2),
MD_GENERICO_1 NUMBER(10,2),
MD_GENERICO_2 NUMBER(10,2),
MD_GENERICO_3 NUMBER(10,2),
MD_GENERICO_4 NUMBER(10,2),
MD_GENERICO_5 NUMBER(10,2),
MD_GENERICO_6 NUMBER(10,2),
MD_GENERICO_7 NUMBER(10,2),
MD_GENERICO_8 NUMBER(10,2),
MD_GENERICO_9 NUMBER(10,2),
MD_GENERICO_10 NUMBER(10,2)
);

ALTER TABLE MKT_PS_AGG_VTA_PEP_REG
ADD CONSTRAINT MKT_PS_AGG_VTA_PEP_REG_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);


ALTER TABLE MKT_PS_AGG_VTA_PEP_REG
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_REGION,
FK_CANAL_RM1,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_PEP
);

--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
-----------------------------------TABLAS DE HECHOS AGG A ESTADO----------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------


-- TABLA DE HECHOS OBJETIVOS DE COBERTURAS GEC SKU 

CREATE TABLE MKT_PS_AGG_COB_GEC_SKU_EDO(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_GEC NVARCHAR2(3),
FK_SKU NVARCHAR2(18),
MD_CLIENTES NUMBER(10,2),
MD_COBERTURA NUMBER(10,2)
);


ALTER TABLE MKT_PS_AGG_COB_GEC_SKU_EDO
ADD CONSTRAINT MKT_PS_AGG_COB_GEC_SKU_EDO_P
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_PS_AGG_COB_GEC_SKU_EDO
ADD CONSTRAINT MKT_PS_AGG_COB_GEC_SKU_EDO_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);

ALTER TABLE MKT_PS_AGG_COB_GEC_SKU_EDO
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_CANAL_RM1,
FK_PREVENTA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_GEC,
FK_SKU
);


-- TABLA DE HECHOS OBJETIVOS DE COBERTURAS GEC PEP 

CREATE TABLE MKT_PS_AGG_COB_GEC_PEP_EDO(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_GEC NVARCHAR2(3),
FK_PEP NVARCHAR2(22),
MD_CLIENTES NUMBER(10,2),
MD_COBERTURA NUMBER(10,2)
);


ALTER TABLE MKT_PS_AGG_COB_GEC_PEP_EDO
ADD CONSTRAINT MKT_PS_AGG_COB_GEC_PEP_EDO_P
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_PS_AGG_COB_GEC_PEP_EDO
ADD CONSTRAINT MKT_PS_AGG_COB_GEC_PEP_EDO_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);

ALTER TABLE MKT_PS_AGG_COB_GEC_PEP_EDO
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_CANAL_RM1,
FK_PREVENTA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_GEC,
FK_PEP
);
-----------
-----------
-----------
-----------



-- TABLA DE HECHOS OBJETIVOS DE COBERTURAS SKU 

CREATE TABLE MKT_PS_AGG_COB_SKU_EDO(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MD_CLIENTES NUMBER(10,2),
MD_COBERTURA NUMBER(10,2)
);


ALTER TABLE MKT_PS_AGG_COB_SKU_EDO
ADD CONSTRAINT MKT_PS_AGG_COB_SKU_EDO_P
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_PS_AGG_COB_SKU_EDO
ADD CONSTRAINT MKT_PS_AGG_COB_SKU_EDO_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);

ALTER TABLE MKT_PS_AGG_COB_SKU_EDO
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_CANAL_RM1,
FK_PREVENTA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_SKU
);


-- TABLA DE HECHOS OBJETIVOS DE COBERTURAS GEC PEP 

CREATE TABLE MKT_PS_AGG_COB_PEP_EDO(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PREVENTA NUMBER(10,0),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
--FK_GEC NVARCHAR2(3),--*************************************
FK_PEP NVARCHAR2(22),
MD_CLIENTES NUMBER(10,2),
MD_COBERTURA NUMBER(10,2)
);


ALTER TABLE MKT_PS_AGG_COB_PEP_EDO
ADD CONSTRAINT MKT_PS_AGG_COB_PEP_EDO_P
FOREIGN KEY(FK_PREVENTA)
REFERENCES MKT_LZ_DIM_TIPO_PREVENTA(PK_PREVENTA);

ALTER TABLE MKT_PS_AGG_COB_PEP_EDO
ADD CONSTRAINT MKT_PS_AGG_COB_PEP_EDO_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);

ALTER TABLE MKT_PS_AGG_COB_PEP_EDO
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_CANAL_RM1,
FK_PREVENTA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_PEP
);



-------------------------
-------------------------
------------------------
-- TABLA DE HECHOS DE INDICADORES DE VENTAS SKU


CREATE TABLE MKT_PS_AGG_VTA_SKU_PV_EDO(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PLAN_VISITA NVARCHAR2(3),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MD_CF_OBJ NUMBER(10,2),
MD_CFC_OBJ NUMBER(10,2),
MD_CU_OBJ NUMBER(10,2),
MD_PIEZAS_OBJ NUMBER(10,2),
MD_REDENCION NUMBER(10,2),
MD_DESCUENTO NUMBER(10,2),
MD_CF_CONV NUMBER(10,2),
MD_PIEZAS_CONV NUMBER(10,2),
MD_CF_REAL NUMBER(10,2)
);

ALTER TABLE MKT_PS_AGG_VTA_SKU_PV_EDO
ADD CONSTRAINT MKT_PS_AGG_VTA_SKU_PV_EDO_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);


ALTER TABLE MKT_PS_AGG_VTA_SKU_PV_EDO
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_CANAL_RM1,
FK_PLAN_VISITA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_SKU
);


-- TABLA DE HECHOS DE INDICADORES DE VENTAS PEP


CREATE TABLE MKT_PS_AGG_VTA_PEP_PV_EDO(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_PLAN_VISITA NVARCHAR2(3),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_PEP NVARCHAR2(22),
MD_CF_OBJ NUMBER(10,2),
MD_CFC_OBJ NUMBER(10,2),
MD_CU_OBJ NUMBER(10,2),
MD_PIEZAS_OBJ NUMBER(10,2),
MD_REDENCION NUMBER(10,2),
MD_DESCUENTO NUMBER(10,2),
MD_CF_CONV NUMBER(10,2),
MD_PIEZAS_CONV NUMBER(10,2),
MD_CF_REAL NUMBER(10,2)
);

ALTER TABLE MKT_PS_AGG_VTA_PEP_PV_EDO
ADD CONSTRAINT MKT_PS_AGG_VTA_PEP_PV_EDO_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);


ALTER TABLE MKT_PS_AGG_VTA_PEP_PV_EDO
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_CANAL_RM1,
FK_PLAN_VISITA,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_PEP
);


-------------------------
-------------------------
------------------------
-- TABLA DE HECHOS DE INDICADORES DE VENTAS SKU


CREATE TABLE MKT_PS_AGG_VTA_SKU_EDO(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_SKU NVARCHAR2(18),
MD_CF_OBJ NUMBER(10,2),
MD_CFC_OBJ NUMBER(10,2),
MD_CU_OBJ NUMBER(10,2),
MD_PIEZAS_OBJ NUMBER(10,2),
MD_REDENCION NUMBER(10,2),
MD_DESCUENTO NUMBER(10,2),
MD_CF_CONV NUMBER(10,2),
MD_PIEZAS_CONV NUMBER(10,2),
MD_CF_REAL NUMBER(10,2),
MD_GENERICO_1 NUMBER(10,2),
MD_GENERICO_2 NUMBER(10,2),
MD_GENERICO_3 NUMBER(10,2),
MD_GENERICO_4 NUMBER(10,2),
MD_GENERICO_5 NUMBER(10,2),
MD_GENERICO_6 NUMBER(10,2),
MD_GENERICO_7 NUMBER(10,2),
MD_GENERICO_8 NUMBER(10,2),
MD_GENERICO_9 NUMBER(10,2),
MD_GENERICO_10 NUMBER(10,2)
);

ALTER TABLE MKT_PS_AGG_VTA_SKU_EDO
ADD CONSTRAINT MKT_PS_AGG_VTA_SKU_EDO_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);


ALTER TABLE MKT_PS_AGG_VTA_SKU_EDO
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_CANAL_RM1,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_SKU
);


-- TABLA DE HECHOS DE INDICADORES DE VENTAS PEP


CREATE TABLE MKT_PS_AGG_VTA_PEP_EDO(
FK_PERIODO_INICIO NVARCHAR2(10),
FK_PERIODO_FIN NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_CANAL_RM1 NVARCHAR2(30),
FK_CATEGORIA NVARCHAR2(30),
FK_RETORNABILIDAD NVARCHAR2(10),
FK_EMPAQUE NVARCHAR2(30),
FK_TAMANO NVARCHAR2(30),
FK_CLAVE_PROMO NVARCHAR2(10),
FK_PROMOCION NUMBER(10,0),
FK_PEP NVARCHAR2(22),
MD_CF_OBJ NUMBER(10,2),
MD_CFC_OBJ NUMBER(10,2),
MD_CU_OBJ NUMBER(10,2),
MD_PIEZAS_OBJ NUMBER(10,2),
MD_REDENCION NUMBER(10,2),
MD_DESCUENTO NUMBER(10,2),
MD_CF_CONV NUMBER(10,2),
MD_PIEZAS_CONV NUMBER(10,2),
MD_CF_REAL NUMBER(10,2),
MD_GENERICO_1 NUMBER(10,2),
MD_GENERICO_2 NUMBER(10,2),
MD_GENERICO_3 NUMBER(10,2),
MD_GENERICO_4 NUMBER(10,2),
MD_GENERICO_5 NUMBER(10,2),
MD_GENERICO_6 NUMBER(10,2),
MD_GENERICO_7 NUMBER(10,2),
MD_GENERICO_8 NUMBER(10,2),
MD_GENERICO_9 NUMBER(10,2),
MD_GENERICO_10 NUMBER(10,2)
);

ALTER TABLE MKT_PS_AGG_VTA_PEP_EDO
ADD CONSTRAINT MKT_PS_AGG_VTA_PEP_EDO_PR
FOREIGN KEY(FK_PROMOCION)
REFERENCES MKT_PS_DIM_PROMOCION(PK_PROMOCION);


ALTER TABLE MKT_PS_AGG_VTA_PEP_EDO
ADD PRIMARY KEY(
FK_PERIODO_INICIO,
FK_PERIODO_FIN,
FK_ESTADO,
FK_CANAL_RM1,
FK_CLAVE_PROMO,
FK_PROMOCION,
FK_PEP
);



------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
----------------------------------TABLAS DE HECHOS DE TRANSACCIONES ----------------------------
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
--SELECT * FROM MKT_PS_ST_MB58;
--TABLA DE HECHOS MB58
CREATE TABLE MKT_PS_FACT_MB58(
PK_REGISTRO NUMBER(30),
FK_CENTRO NVARCHAR2(4),
FK_CLIENTE NVARCHAR2(10),
FK_SKU NVARCHAR2(18),
MV_UNIDAD NVARCHAR2(3),
MD_LIBRE_UTL NUMBER(10)
);


-- ALTER TABLE MKT_PS_FACT_MB58
-- ADD PRIMARY KEY(
-- FK_CENTRO,
-- FK_CLIENTE,
-- FK_SKU
-- );

-- TABLA DE HECHOS MB51

CREATE TABLE MKT_PS_FACT_MB51(
PK_REGISTRO NUMBER(10),
FK_PERIODO_DOC NVARCHAR2(10),
FK_ESTADO NVARCHAR2(3),
FK_REGION NVARCHAR2(5),
FK_CENTRO NVARCHAR2(6),
FK_UO NVARCHAR2(6),
FK_USUARIO NUMBER(10,0),
FK_ALMACEN NUMBER(10),
FK_REFERENCIA NUMBER(10),
FK_MATERIAL NUMBER(10),
FK_DOC_MATERIAL NUMBER(10),
FK_PEDIDO NUMBER(10),
MV_MOTIVO_MOV NUMBER(10,2),
MV_HORA NVARCHAR2(30),
MD_CTD NUMBER(10,2),
MD_IMPORTE_ML NUMBER(10,2)
);


ALTER TABLE MKT_PS_FACT_MB51
ADD CONSTRAINT MKT_PS_FACT_MB51_USR
FOREIGN KEY(FK_USUARIO)
REFERENCES MKT_PS_DIM_USUARIO_MB51	(PK_USUARIO);

ALTER TABLE MKT_PS_FACT_MB51
ADD CONSTRAINT MKT_PS_FACT_MB51_AL
FOREIGN KEY(FK_ALMACEN)
REFERENCES MKT_PS_DIM_ALMACEN_MB51	(PK_ALMACEN);

ALTER TABLE MKT_PS_FACT_MB51
ADD CONSTRAINT MKT_PS_FACT_MB51_RF
FOREIGN KEY(FK_REFERENCIA)
REFERENCES MKT_PS_DIM_REFERENCIA_MB51(PK_REFERENCIA);

ALTER TABLE MKT_PS_FACT_MB51
ADD CONSTRAINT MKT_PS_FACT_MB51_MTL
FOREIGN KEY(FK_MATERIAL)
REFERENCES MKT_PS_DIM_MATERIAL_MB51(PK_MATERIAL);

ALTER TABLE MKT_PS_FACT_MB51
ADD CONSTRAINT MKT_PS_FACT_MB51_DOCM
FOREIGN KEY(FK_DOC_MATERIAL)
REFERENCES MKT_PS_DIM_DOC_MATERIAL_MB51(PK_DOC_MATERIAL);

ALTER TABLE MKT_PS_FACT_MB51
ADD CONSTRAINT MKT_PS_FACT_MB51_PD
FOREIGN KEY(FK_PEDIDO)
REFERENCES MKT_PS_DIM_PEDIDO_MB51(PK_PEDIDO);

ALTER TABLE MKT_PS_FACT_MB51
ADD PRIMARY KEY(
PK_REGISTRO,
FK_PERIODO_DOC,
FK_UO,
FK_USUARIO,
FK_ALMACEN,
FK_REFERENCIA,
FK_MATERIAL,
FK_DOC_MATERIAL,
FK_PEDIDO
);


COMMIT;